6213 Спиридонова К.С Lab-var6
itsecd/python pull request #101
Opened 2023-12-20 23:50 UTC by kksseonn

2023-12-21 10:44 UTC, alxmcs requested changes
![image](https://github.com/itsecd/python/assets/70561974/71080f37-f489-4473-9a0f-ddefe9193306)
А куда train accuracy делся?

И было бы неплохо вписать в ноутбук какие-нибудь выводы на основе проведенных экспериментов и оценить работу итоговой модели

2023-12-21 16:46 UTC, alxmcs requested changes
Может я куда-то не туда смотрю, но  все еще не вижу на графике training accuracy, только одинокие validation accuracy

2023-12-21 16:51 UTC, kksseonn commented
> Может я куда-то не туда смотрю, но все еще не вижу на графике training accuracy, только одинокие validation accuracy

еще не переделала ноутбук :(

2023-12-21 16:53 UTC, alxmcs reviewed
А, прошу прощения.
Был нотификейшен о коммите в pr, запроса повторного ревью не было.
Зря быканул.

2023-12-22 10:03 UTC, alxmcs approved these changes
Зачтено, однако:

>Слишком высокий learning rate (0.1) приводит к расходиму модели. 

<img src="https://github.com/itsecd/python/assets/70561974/b2d1309b-38f4-4758-b04a-e2a928dea4ab)" width=200/>

2023-12-22 10:03 UTC, closed without merging