6213 Теребилкин Д.И. Лаб.5 Вар.9
itsecd/python pull request #106
Opened 2023-12-21 16:59 UTC by Quyntrd

Честно говоря, я все еще пытаюсь понять, что я вообще делаю, каждый раз запуская ipynb, я как будто бы стреляю себе в колено с ружья 12 калибра

2023-12-21 17:02 UTC, alxmcs requested changes
Ну когда что-нибудь заработает, запрашивай ревью

2023-12-22 10:44 UTC, alxmcs requested changes
Если бы я получил такие результаты, у меня возникло бы подозрение насчет того, все ли я делаю правильно:
![image](https://github.com/itsecd/python/assets/70561974/c9bfaff9-0f58-491e-ad4a-f4193537bca0)


Твоя задача - провести 9 экспериментов по обучению сети. В результате каждого эксперимента у тебя должен получиться отдельный обученный экземпляр модели.
Еще раз - 1 модель, 9 экземпляров, 9 экспериментов.

В текущем варианте кода у тебя 1 модель, 1 ее экземпляр и он обучается 9 раз подряд, накапливая результаты обучения. Поэтому и графики выглядят как кардиограмма трупа к концу экспериментов:
![image](https://github.com/itsecd/python/assets/70561974/01bf3cbb-5e1c-41e6-8bf1-e7572d2b0aac)

2023-12-22 11:48 UTC, Quyntrd commented
Я поменял расположение создания модели, теперь она создается на каждом цикле при тестировании разных learning rate и batch size, и сейчас графики имеют нормальный вид. (Я еще до запрашивания реквеста понял что-то не так с обучением модели, но только сейчас понял, что надо было поменять)

2023-12-22 12:03 UTC, alxmcs requested changes
Смотрим графики:
![image](https://github.com/itsecd/python/assets/70561974/6e2a52d8-46ed-4cfe-b2dc-bb41661ed0f1)
На обучающей выборке все идет хорошо, на валидационной - сразу все плохо и и лучше не становится. Значит что-то не так с данными:
Вот тут у тебя есть шаффл, это здоровая идея - перемешивать выборки при обучении:
![image](https://github.com/itsecd/python/assets/70561974/708fe3d4-2474-4d6f-9a7f-46645edfec83)
Только вот при разделении на обучающую, валидационную и тестовую выборки шаффла не было:
![image](https://github.com/itsecd/python/assets/70561974/a32ec00a-03f4-4830-9c44-61cdb356131f)
А датасет у тебя сортированный  по меткам:
![image](https://github.com/itsecd/python/assets/70561974/cb062b43-529c-49e7-871d-74233bcd7e70)
Соответственно, при делении датасета на выборки в обучающую упали только метки 0, а в валидационную - только метки 1 (тут несколько утрировано, но, думаю, идею ты понял). А для качественного обучения модели во всех выборках должны быть представлены все классы в равной (+/-) степени.

2023-12-22 12:18 UTC, alxmcs reviewed
У тебя, судя по данным, получается, бинарная классификация отзывов - отзывы на 4 звезды ты пробуешь отличать от 5 звезд (если я верно понял). 
Звучит тяжеловато. Отзывы на 1 звезд от 5 звезд было бы пробовать отличить реалистичнее, там будет явно разный вокабуляр.

Но я не заставляю переделывать датасет, просто держу в курсе

2023-12-22 12:25 UTC, Quyntrd commented
Я на самом деле думаю, что это происходит из-за датасета, возможно лучше будет разделить таким образом, отзывы с 4 и 5 звездами ставить им класс 1, а отзывам с 1-3 звездами класс 0, тогда он будет отличать отзывы, гипотетически на хороший/плохой

2023-12-23 08:05 UTC, alxmcs approved these changes
Я тут освежил себе память по документации sklearn и понял, что зря быканул - train_test_split по дефолту перемешивает выборки

2023-12-23 08:05 UTC, closed without merging