6213-100503D Корся Ева Дмитриевна Лаб.1  Вар.9
itsecd/python pull request #11
Opened 2023-10-14 18:32 UTC by IvaKorsya

найти банк с большим количеством отзывов, сохранять в текстовые файлы отзывы о нем(частично или полностью, у меня выполнена  "усложненная версия" с сохранением полного отзыва.

2023-10-14 18:32 UTC, IvaKorsya commented
найти банк с большим количеством отзывов, сохранять в текстовые файлы отзывы о нем(частично или полностью, у меня выполнена "усложненная версия" с сохранением полного отзыва.

2023-10-14 18:34 UTC, IvaKorsya commented
найти банк с большим количеством отзывов, сохранять в текстовые файлы отзывы о нем(частично или полностью, у меня выполнена "усложненная версия" с сохранением полного отзыва.

2023-10-15 09:02 UTC, alxmcs requested changes

2023-10-15 09:02 UTC, alxmcs commented on Lab1/lab1-var9-korsya-6213.py
> +def main():
Меня очень калит, когда народ делает в модуле функцию `main()`, в которой нет входных параметров, зато присутствует куча захардкоженных значений. 
Из этой функции тебе нужно декомпозировать части кода:
1) которая занимается подготовкой инфраструктуры под сохранение результатов (и выделить в отдельную функцию)
2) которая занимается обработкой непосредственно страниц в цикле (и выделить в отдельную функцию),
3) которая занимается непосредственно запуском обработки (и убрать под `if __name__ == '__main__':`)

2023-10-15 12:56 UTC, IvaKorsya commented
декомпозирована main, создание папок обрабатывается с помощью исключений в отдельной функции, добавлены аргументы argparse

2023-10-15 12:59 UTC, IvaKorsya commented
ссылка, имя директории, количество просматриваемых страниц передаются через консоль, но в функции есть аргументы и по умолчанию

2023-10-15 13:17 UTC, IvaKorsya commented
имя модуля изменено

2023-10-15 14:28 UTC, alxmcs approved these changes

2023-11-16 07:05 UTC, closed without merging