6213 Ксеневич Максим Лаб 5 Вар 10
itsecd/python pull request #111
Opened 2023-12-22 11:06 UTC by maeosha

пятая лаба это испытание свыше перед чем-то великим??

2023-12-22 11:31 UTC, alxmcs requested changes
Меня смущает следующее (как и в #105, #106, #107, #108):
![image](https://github.com/itsecd/python/assets/70561974/db307ee8-c616-49f1-aba3-5ca663ee5db7)
Экземпляр модели у тебя один, экспериментов 9. Соответственно, обучается модель 9 раз подряд, при этом я не вижу кода, где сбрасываются ее веса перед началом следующего эксперимента (может я и проглядел это в коде). 
`model.train()`, например, никакие веса не сбрасывает, а только меняет поведение определенных слоев, типа дропаута, см. в [документации](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.train).
Получается, что модель дообучается 9 раз, а не обучается с нуля 9 раз.
Тут нужно либо:
* сбрасывать веса перед экспериментом,
* заводить новый экземпляр модели на каждый эксперимент.

2023-12-22 11:31 UTC, alxmcs commented on Untitled1.ipynb
Этот ноутбук, наверное, лишний

2023-12-22 11:47 UTC, maeosha commented
прошу прощения, уже поправил, сейчас код отработает и пришлю. Надо же как наши лабы похожи, не зря второй год вместе учимся

2023-12-23 07:57 UTC, alxmcs requested changes
На тестовой выборке у тебя все хорошо, а на валидационной - все плохо
![image](https://github.com/itsecd/python/assets/70561974/2cc3fb17-d936-46b1-bc9f-0adc4a201cdf)
Это скорее всего происходит потому, что ты не перемешиваешь датасет при разделении его на выборки:
![image](https://github.com/itsecd/python/assets/70561974/3c735a6a-e006-4f9a-ab6e-64ede096d66d)
Чтобы сеть обучилась нормально, надо чтобы все классы были представлены в +/- равномерно во всех выборках

2023-12-23 08:08 UTC, alxmcs approved these changes
Освежил память по документации sklearn  - train_test_split по дефолту перемешивает выборки при создании. Так что претензия снимается

2023-12-23 08:08 UTC, closed without merging