Каляганов ДД 6511 1 вариант
itsecd/python pull request #113
Opened 2024-04-13 17:37 UTC by winslow63

2024-04-16 07:55 UTC, alxmcs requested changes
Не уметь на 5 курсе пользоваться гитом - несмываемый позор:
![image](https://github.com/itsecd/python/assets/70561974/ac3fc434-41e9-4b9a-a6ca-a373a60d74a2)
Я ожидаю видеть правки к этому pr в виде грамотно оформленных коммитов, а не через аплоад файлов в веб-интерфейсе.

2024-04-16 07:55 UTC, alxmcs commented on Lab3/mian_window.py
> +        #self.tuple_list=[]
Закомменченный код убрать

2024-04-16 07:55 UTC, alxmcs commented on Lab3/mian_window.py
> +if __name__ == '__main__':
Нарушение РЕР - пустые строки

2024-04-16 07:55 UTC, alxmcs commented on Lab3/mian_window.py
> +    def split_xy(self):
Нет докстринга, нет тайпхинтов, нет обработки исключений операций

2024-04-16 07:55 UTC, alxmcs commented on Lab3/mian_window.py
> +    def split_by_week(self):
Нет докстринга, нет тайпхинтов, нет обработки исключений операций

2024-04-16 07:55 UTC, alxmcs commented on Lab3/mian_window.py
> +    def get_data(self):
Нет докстринга, нет тайпхинтов, нет обработки исключений операций

2024-04-16 07:55 UTC, alxmcs commented on Lab3/mian_window.py
> +    def file(self):
Нет докстринга, нет тайпхинтов, нет обработки исключений операций

2024-04-16 07:55 UTC, alxmcs commented on Lab3/nextt.py
Нарушение РЕР- именование модуля

В коде полностью отсутствует логирование

2024-04-16 07:55 UTC, alxmcs commented on Lab3/nextt.py
> +def next(tuple):
Нарушение РЕР - пустые строки

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +def check_file_existence(directory, filename):
Нарушение РЕР - пустые строки

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +def Y(i,folderpath_search):
Нарушение РЕР - пустые строки

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +    #Y=folderpath_search.replace("X.csv", "")
Закомменченный код убрать

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +                # with open("D:\\3\\"+filename) as csvfile:
Закомменченный код убрать

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +def check_file_extension(filename, desired_extension):
Нет докстринга, нет тайпхинтов

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +def get_data_by_date(data, folderpath_search):
Нет докстринга, нет тайпхинтов

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +        with open(f'{folderpath_search}/course.csv') as csvfile:
Захардкоженное имя файла вынести в параметры

Конкатенация путей только через `os.path.join()`

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +    if check_file_existence(folderpath_search, 'X.csv'):
Захардкоженное имя файла вынести в параметры

Конкатенация путей только через `os.path.join()`

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +        with open(f'{folderpath_search}/X.csv') as csvfile:
Захардкоженное имя файла вынести в параметры

Конкатенация путей только через `os.path.join()`

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +            with open(f'{folderpath_search}/{filename}') as csvfile:
Конкатенация путей только через `os.path.join()`

2024-04-16 07:55 UTC, alxmcs commented on Lab3/search.py
> +    if check_file_existence(folderpath_search,'course.csv'):
Захардкоженное имя файла вынести в параметры

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +    '''1'''
Убрать

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +    '''3'''
Убрать

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +    '''5'''
Убрать

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +    '''6'''
Убрать

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +    '''7'''
Убрать

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +    '''8'''
Убрать

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +    deviation_value = 0.3# значение отклонения от среднего значения курса
Передавать через argparse

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +    plt.figure(figsize=(10, 6))
Убрать лишние пустые строки

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +import matplotlib.pyplot as plt
Убрать лишние пустые строки

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +def filter_by_date_range(df, start_date, end_date):
Нарушение РЕР - число пустых строк

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +def filter_by_month(df):
Нарушение РЕР - число пустых строк

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +def course_change(dataframe):
Нарушение РЕР - число пустых строк

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +if __name__ == '__main__':
Нарушение РЕР - число пустых строк

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +def filter_by_mean_deviation(df, deviation_value):
Нет докстринга, нет тайпхинтов

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +def plot_currency_monthly_stats(dataframe, month):
Нет докстринга, нет тайпхинтов

2024-04-16 07:55 UTC, alxmcs commented on Lab4/main.py
> +def course_change(dataframe):
Нет докстринга, нет тайпхинтов

2024-04-17 19:52 UTC, winslow63 commented on Lab2/five.py
> +                break
как должно выглядеть меню?

2024-04-18 06:07 UTC, alxmcs commented on Lab2/five.py
> +                break
В этом репозитории 100+ принятых пул-риквестов
Посмотри примеры там

2024-04-19 07:29 UTC, alxmcs requested changes

2024-04-19 07:29 UTC, alxmcs commented on Lab2/one.py
> +        with open(args.y,mode="a") as csvX:
Передавать путь к файлу в виде входного параметра функции и описать его в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab2/one.py
> +        with open(args.x,mode="a") as csvX:
Передавать путь к файлу в виде входного параметра функции и описать его в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab2/three.py
> +    '''путь к файлу n'''
Нет описания параметров в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab2/three.py
> +    '''заполнение первой строки в ссв'''
Нет описания параметров в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab2/three.py
> +def first_line_N(name_file)->None:
Нарушение РЕР в именовании функции, нет тайпхинта входного параметра

2024-04-19 07:29 UTC, alxmcs commented on Lab2/three.py
> +def separation_files_N()->None:
Нарушение РЕР в именовании функции

2024-04-19 07:29 UTC, alxmcs commented on Lab2/three.py
> +import argparse
Нарушение порядка импортов

2024-04-19 07:29 UTC, alxmcs commented on Lab2/three.py
> +    with open(args.csv) as csvfile:
Передавать путь к файлу в виде входного параметра функции и описать его в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab2/three.py
> +    with open(args.csv) as csvfile:
Передавать путь к файлу в виде входного параметра функции и описать его в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab2/three.py
Все еще не исправлено название модуля

Нет логирования. Нет обработки исключений при работе с файловыми потоками (что применимо ко всему коду в этом pr в принципе)

2024-04-19 07:29 UTC, alxmcs commented on Lab2/zero.py
Этого скрипта не должно быть в проекте второй лабораторной в принципе. В ней осуществляется работа с результатами, полученными в ходе первой лабораторной. Удалить.

2024-04-19 07:29 UTC, alxmcs commented on Lab2/two.py
> +import os
Нарушение порядка импортов

2024-04-19 07:29 UTC, alxmcs commented on Lab2/two.py
> +    '''путь к файлу n'''
Нет описания параметров в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab2/two.py
> +    '''заполнение первой строки в ссв'''
Нет описания параметров в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab2/two.py
> +    lines = 0# строки в ссв файле
Инлайн комменты убрать

2024-04-19 07:29 UTC, alxmcs commented on Lab2/two.py
> +    with open(args.csv) as csvfile:
Передавать путь к файлу в виде входного параметра функции и описать его в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab2/two.py
> +    with open(args.csv) as csvfile:
Передавать путь к файлу в виде входного параметра функции и описать его в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab2/two.py
> +def N_files()->None:
Нарушение РЕР в именовании функции

2024-04-19 07:29 UTC, alxmcs commented on Lab3/functions.py
> +                    file.write(f'http://www.cbr.ru/currency_base/daily/?UniDbQuery.Posted=True&UniDbQuery.To={rov['Дата'].replace("-",".")}\n')
Захардкоженный урл все еще не вынесен в параметры или константы

2024-04-19 07:29 UTC, alxmcs commented on Lab3/functions.py
> +    #new_filename = filename[1:]
Закомменченный код убрать

2024-04-19 07:29 UTC, alxmcs commented on Lab3/functions.py
> +    создание в директории поддиректорий
В докстринге нет описания параметров

2024-04-19 07:29 UTC, alxmcs commented on Lab3/functions.py
> +    """существование файла в директории"""
В докстринге нет описания параметров

2024-04-19 07:29 UTC, alxmcs commented on Lab3/functions.py
> +    """создание файла анотации"""
В докстринге нет описания параметров

2024-04-19 07:29 UTC, alxmcs commented on Lab3/functions.py
> +        file= os.path.join(folderpath,csvs)
`os.path.join()` сам ставит корректные слеши в путях в зависимости от ОС, на которой запускается код. Убрать этот кошмар - `+ '/'`

2024-04-19 07:29 UTC, alxmcs commented on Lab3/mian_window.py
Это все еще `mian_window`, а не `main_window`

2024-04-19 07:29 UTC, alxmcs commented on Lab3/mian_window.py
> +import nextt
Порядок импортов все еще нарушен

2024-04-19 07:29 UTC, alxmcs commented on Lab3/nextt.py
> +    """поиск минимальной даты в файле"""
В докстринге отсутствует описание параметров

2024-04-19 07:29 UTC, alxmcs commented on Lab3/nextt.py
> +    """вывод списка информации из файла"""
В докстринге отсутствует описание параметров

2024-04-19 07:29 UTC, alxmcs commented on Lab3/search.py
> +    """проверака существует ли файл с расширением .csv в директории"""
В докстринге отсутствует описание параметров

2024-04-19 07:29 UTC, alxmcs commented on Lab3/search.py
> +    """поиск информации в игрик файле"""
В докстринге отсутствует описание параметров

2024-04-19 07:29 UTC, alxmcs commented on Lab3/search.py
> +    with open(f'{folderpath_search}/Y.csv') as csvfile:
Это замечание все еще не исправлено

2024-04-19 07:29 UTC, alxmcs commented on Lab3/search.py
> +        file = os.path.join(folderpath, args.x)
Некорректное использование `os.path.join()`

2024-04-19 07:29 UTC, alxmcs commented on Lab3/search.py
> +        file = os.path.join(folderpath, args.csv)
Некорректное использование `os.path.join()`

2024-04-19 07:29 UTC, alxmcs commented on Lab3/search.py
> +import csv
Нарушение порядка импорта

2024-04-19 07:29 UTC, alxmcs commented on Lab3/three.py
Я уже писал в прошлом ревью, что код из 2 лабораторной не должен копироваться в 3 лабораторную. Он должен быть проимпортирован. Как это сделать, можно посмотреть в 100+ принятых pr в этом репозитории

2024-04-19 07:29 UTC, alxmcs commented on Lab3/two.py
Я уже писал в прошлом ревью, что код из 2 лабораторной не должен копироваться в 3 лабораторную. Он должен быть проимпортирован. Как это сделать, можно посмотреть в 100+ принятых pr в этом репозитории

2024-04-19 07:29 UTC, alxmcs commented on Lab3/zero.py
Я уже писал в прошлом ревью, что код из 2 лабораторной не должен копироваться в 3 лабораторную. Он должен быть проимпортирован. Как это сделать, можно посмотреть в 100+ принятых pr в этом репозитории

2024-04-19 07:29 UTC, alxmcs commented on Lab4/main.py
> +    """DataFram отфильтрованный по датам DataFram"""
Нет описания параметров в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab4/main.py
> +    """DataFrame отфильтрованный по значению отклонения от среднего значения курса """
Нет описания параметров в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab4/main.py
> +    """график изменения курса за весь период"""
Нет описания параметров в докстринге

2024-04-19 07:29 UTC, alxmcs commented on Lab4/main.py
> +    df = pd.read_csv("course.csv",encoding='cp1251', delimiter=';')
Все еще отсутствует аргумент argparse для передачи пути к файлу с данными

2024-04-19 07:29 UTC, alxmcs commented on Lab5/lab5.ipynb
С 5 лабораторной ничего не произошло - в ноутбуке все еще нет выводов о качестве работы и качестве обучения построенной модели

2024-04-25 05:36 UTC, alxmcs requested changes
Стало определенно лучше, но правки все еще нужны

2024-04-25 05:36 UTC, alxmcs commented on Lab2/class_iterators_searching.py
> +class search_undivided_files:
Если внимательно посмотреть РЕР, то выяснится, что функции и методы именуются снейк кейсом, а вот имена классов - кемел кейсом
![image](https://github.com/itsecd/python/assets/70561974/d062774a-8289-49d8-8562-a3f4f8195be4)

2024-04-25 05:36 UTC, alxmcs commented on Lab2/class_iterators_searching.py
> +class ssearch_in_split_files:
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/class_iterators_searching.py
> +    def __next__(self):
Лишние пустые строки - между функциями по 2, между методами класса - по 1

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +                print("None")
Зачем print, если уже подключен logging? Можно просто добавить еще одну конфигурацию для логирования в консоль помимо файла

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +        print("Файл не найден.")
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +                print("None")
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +        print("Файл не найден.")
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +        print("Файл не найден.")
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +                    print(rov['Информация'])
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +                        print(rov['Информация'])
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +        print("Папка не найдена.")
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +            print("None")
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +                        print(rov['Информация'])
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +            print("None")
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +        print("Папка не найдена.")
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +        print("Файл не найден.")
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +        print (tuple_element)
Аналогично

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +def search_files_x_y(search_date:datetime,file_x:str,file_y:str)->None:
Пустых строк должно быть 2

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +def search_files_week(search_date:datetime,file_week:str)->None:
И тут тоже

2024-04-25 05:36 UTC, alxmcs commented on Lab2/date_search.py
> +def next(tuple:list)->list:
И тут тоже

2024-04-25 05:36 UTC, alxmcs commented on Lab3/functions_creating_anotype_directory.py
> +    url="http://www.cbr.ru/currency_base/daily/?UniDbQuery.Posted=True&UniDbQuery.To="
`url` захардкожен. Либо вынести его в константы модуля, либо в параметр функции со значением по умолчанию

2024-04-25 05:36 UTC, alxmcs commented on Lab3/main_window.py
> +    def __init__(self)->None:
Многовато пустых строк

2024-04-25 05:36 UTC, alxmcs commented on Lab3/main_window.py
> +    def choose_folder(self)->None:
Аналогично - между методами класса должно быть по 1 пустой строке

2024-04-25 05:36 UTC, alxmcs commented on Lab3/main_window.py
> +    def split_xy(self)->None:
Аналогично - между методами класса должно быть по 1 пустой строке

2024-04-25 05:36 UTC, alxmcs commented on Lab3/main_window.py
> +    def split_by_year(self)->None:
Аналогично - между методами класса должно быть по 1 пустой строке

2024-04-25 05:36 UTC, alxmcs commented on Lab3/main_window.py
> +    def split_by_week(self)->None:
Аналогично - между методами класса должно быть по 1 пустой строке

2024-04-25 05:36 UTC, alxmcs commented on Lab3/main_window.py
> +    def directory(self)->None:
Аналогично - между методами класса должно быть по 1 пустой строке

2024-04-25 05:36 UTC, alxmcs commented on Lab3/main_window.py
> +    def get_data(self)->None:
Аналогично - между методами класса должно быть по 1 пустой строке

2024-04-25 05:36 UTC, alxmcs commented on Lab3/main_window.py
> +    def file(self)->None:
Аналогично - между методами класса должно быть по 1 пустой строке

2024-04-25 05:36 UTC, alxmcs commented on Lab3/main_window.py
> +    def next(self)->None:
Аналогично - между методами класса должно быть по 1 пустой строке

2024-04-25 05:36 UTC, alxmcs commented on Lab3/main_window.py
> +    def create_annotation(self)->None:
Аналогично - между методами класса должно быть по 1 пустой строке

2024-04-25 05:36 UTC, alxmcs commented on Lab3/search.py
> +    args = parser.parse_args()
Парсер - это то, что должно находится под `if __name__ == "__main__"` для получения параметров, необходимых для работы софта. Это интерфейсная вещь, ей явно не место внутри бизнес-логики приложения. 

Получаемые тут значения должны быть параметрами самой функции.

2024-04-25 05:36 UTC, alxmcs commented on Lab4/main.py
> +    monthly_data = dataframe[(dataframe['Дата'].dt.month == month) & (dataframe['Дата'].dt.year == 2024)]
Думаю, что летоисчисление продолжится и после 2024 года. Использовать `datetime.now().year`

2024-04-25 05:36 UTC, alxmcs commented on Lab4/main.py
> +    df = pd.read_csv("course.csv",encoding='cp1251', delimiter=';')
Путь до сих пор захардкожен - вынеси его в аргумент для argparse

2024-04-25 05:36 UTC, alxmcs commented on Lab4/main.py
print-ы заменить на logging

2024-04-25 05:36 UTC, alxmcs commented on Lab5/lab5.ipynb
Третье ревью подряд тебе лень добавить еще одну ячейку в ноутбук и написать в ней свои впечатления касательно того, получилась у тебя 5 лаба или нет.

2024-04-25 15:19 UTC, alxmcs approved these changes
В одном месте все еще торчит захардкоженный путь к файлу, но я уже устал писать в каждом ревью об этом. Пора уже это все заканчивать.

Как можно заметить, все 300+ претензий к коду были в основном оформительского характера. Если бы я описывал еще и претензии к коду архитектурного характера, то страница с pr вряд ли могла бы отрендериться.

Но в текущем виде код можно принять.

Ps.Насчет 5 лабы:
> модель ... способна делать относительно точные предсказания
> ![image](https://github.com/itsecd/python/assets/70561974/7223d81c-9e6c-4ff5-b5d3-266436152ffd)

Фиксируем прибыль, так сказатб

2024-04-26 06:28 UTC, closed without merging