6213 Барышников Владислав Сергеевич Лаб.1 Вар.1
itsecd/python pull request #12
Opened 2022-10-13 14:54 UTC by dedrowe

Данная программа получает курс доллара с сайта https://www.cbr-xml-daily.ru/archive/2022/09/08/daily_json.js до максимально возможной даты (08-02-2020) и записывает их в файл dataset.csv

2022-10-14 11:08 UTC, alxmcs reviewed
Без учета пустых строк, докстрингов и requirements.txt, я докопался к каждой 1,8 строке.

Больше всего меня, конечно, позабавил факт, что раньше 8 февраля 2020 года рубля, по твоему мнению, не существовало.

2022-10-14 11:08 UTC, alxmcs commented on Lab1/main.py
> +def take_value(source, temp_dataset):
`take_value` - не самое подходящее название для этой функции. Ты тут не просто 'take' какое-то одно `value`, ты тут парсишь набор жсонов, наполняя значениями из них датасет.

2022-10-14 11:08 UTC, alxmcs commented on Lab1/main.py
> +def file_input(value, data):
`file_input` - не самое подходящее название для данной функции. Я думаю, что с первого курса вам внушали мысль, что названия модулей/классов/методов/функций должны быть репрезентативны, чтобы сторонний человек, который увидит этот код, подумал "Ага, мне понятно, что ты здесь реализовал", а не 
![image](https://user-images.githubusercontent.com/70561974/195832397-7c0cf457-c42f-4606-ab5f-d6bed6445134.png)

2022-10-14 11:12 UTC, alxmcs requested changes
Естественно, необходимо исправить замечания по коду.
В ревью ошибся кнопкой.

2022-10-14 12:30 UTC, alxmcs commented
Еще один момент.
Судя по всему, ты не коммитил из склонированного на твою машину репозитория, а просто перетащил файл через аплоад в веб-интерфейсе гитхаба. 
![image](https://user-images.githubusercontent.com/70561974/195846396-11be051f-f264-49b4-9290-597777a064e8.png)
Не понятно, в таком случае, зачем была отдельная лекция о том, как пользоваться гитом, и зачем я распинался на первых нескольких лабораторных об этой же теме. До тех пор, пока ты не научишься нормально пользоваться гитом, лабораторную я не зачту.

2022-10-17 07:10 UTC, alxmcs requested changes
Стало лучше, осталось исправить некоторые моменты

2022-10-17 07:10 UTC, alxmcs commented on Lab1/main.py
> +    while True:
Ни `logging`, ни `tqdm` в этой секции кода все еще не наблюдаю

2022-10-17 07:10 UTC, alxmcs commented on Lab1/main.py
> +
Пустая строка

2022-10-17 07:10 UTC, alxmcs commented on Lab1/main.py
> +    while True:
33 строка:
```py
while True:
```
37 строка:
```py
if d_page_code['Date'][:10] == min_date
```

Как насчет изначально нормальное условие выходя для цикла написать?

2022-10-17 07:22 UTC, dedrowe commented on Lab1/main.py
> +
если я убираю пустую строку из конца, то мне пишет вот это
![image](https://user-images.githubusercontent.com/112894733/196113656-bcbdf6de-c335-4e8d-ae8b-e15ee21393ae.png)

2022-10-25 08:09 UTC, alxmcs requested changes
Осталось поправить пару мелочей

2022-10-25 08:09 UTC, alxmcs commented on Lab1/main.py
> +
В докстринге нет описания параметра `source`

2022-10-25 08:09 UTC, alxmcs commented on Lab1/main.py
> +
В докстринге параметр `currency` фигурирует как `valute`

2022-10-27 07:00 UTC, alxmcs approved these changes

2022-10-27 07:00 UTC, closed without merging