Лабораторная работа номер 2 вариант 4 Панюшкин Андрей 6213
itsecd/python pull request #14
Opened 2022-10-21 13:33 UTC by Santas7

В данной л/р необходимо было создать 5 файлов под каждый пункт(на базе 1 лабы):
1) создание класса аннотации ( формирование файла аннотации .csv ) 
2) создание копии файлов так чтобы название класса переместилось в название элемента .jpg (classname_0001.jpg....)
3) создание копии файлов так чтобы название элемента теперь рандомно генерировалось (от 0 до 10000)
4) создание функции которая выводит некст элемент класса
5) создание класса итератора на основе пункта (4)

2022-10-25 10:50 UTC, alxmcs requested changes
Общее замечание: здесь явно нужны подробные докстринги с описанием всех параметров. В основном потому, что в коде сооружено методов и параметров явно сверх необходимого. Надо брать бритву Оккама и ~~резать себе вены~~ отсекать лишнее.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/iterator_class.py
> +if __name__ == "__main__":
Если есть желание протестировать какой-то отдельный функционал твоего пакета, то не стоит засорять тестовым кодом скрипты с функциями/классами. Лучше написать юнит-тесты, примитивная библиотека для этого [есть в поставке](https://docs.python.org/3/library/unittest.html).

2022-10-25 10:50 UTC, alxmcs commented on Lab2/copy_elements.py
> +if __name__ == "__main__":
Аналогично.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/next_element.py
> +if __name__ == "__main__":
Аналогично.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/random_of_copy.py
> +if __name__ == "__main__":
Аналогично.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/iterator_class.py
> +class Iterator:
Название класса стоит конкретизировать.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +                path = os.path.abspath(f'{self.dir_name}/{self.class_name}/{i:04d}.jpg')
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +                path = os.path.expanduser(f'{self.dir_name}/{self.class_name}/{i:04d}.jpg')
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +                path = os.path.abspath(f'{self.dir_name}/{self.class_name}_{i:04d}.jpg')
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +                path = os.path.expanduser(f'{self.dir_name}/{self.class_name}_{i:04d}.jpg')
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +                path = os.path.abspath(f'{self.dir_name}/{i:05d}.jpg')
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +                path = os.path.expanduser(f'{self.dir_name}/{i:05d}.jpg')
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +            logging.warning("Error! I can not get path! 0x(((")
Нерепрезентативное сообщение о возникшем исключении без системной информации.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +            logging.warning("Error! Write in this file is failed! 0x(((")
Нерепрезентативное сообщение о возникшем исключении без системной информации.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +            logging.warning("Error! I can not get the path of data! 0x(((")
Нерепрезентативное сообщение о возникшем исключении без системной информации.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +            logging.warning("Error! I can not get the path of data! 0x(((")
Нерепрезентативное сообщение о возникшем исключении без системной информации.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +            logging.warning("Error! I can not get the path of data! 0x(((")
Нерепрезентативное сообщение о возникшем исключении без системной информации.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +            logging.warning("Error forming of csv file! 0x(((")
Нерепрезентативное сообщение о возникшем исключении без системной информации.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +                for i in range(999):
`range(999)` даст 999 элементов, а данных по заданию должно быть 1000 строк

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +            with open(f'{self.dir_name}/annotation.csv', 'a', newline='') as file:
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +                file.close()
При использовании `with` поток закроется автоматически, как только интерпретатор выйдет из скоупа. Вручную закрывать поток не надо.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +                pass
Зачем?

2022-10-25 10:50 UTC, alxmcs commented on Lab2/next_element.py
> +    with open(f'{obj.dir_name}/annotation.csv', 'r', newline='') as file:
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/next_element.py
> +        for i in range(len(tmp)):
Почитай на досуге про regex, в pyhton есть соответствующий [модуль](https://docs.python.org/3/library/re.html), при помощи которого можно можно зарефакторить всю эту порнографию буквально в две строки.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/random_of_copy.py
> +        os.rename(f'{later_dir}/{obj.class_name}/{i + 1:04d}.jpg',
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/random_of_copy.py
> +                  f'{later_dir}/{obj.class_name}/{n:05d}.jpg')
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/random_of_copy.py
> +        shutil.copy(os.path.expanduser(f'{later_dir}/{obj.class_name}/{n:05d}.jpg'), obj.dir_name)
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/random_of_copy.py
> +        os.rename(f'{later_dir}/{obj.class_name}/{n:05d}.jpg',
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/random_of_copy.py
> +                  f'{later_dir}/{obj.class_name}/{i + 1:04d}.jpg')
Конкатенация путей только через `os.path.join`.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/random_of_copy.py
> +
Пустая строка.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/random_of_copy.py
> +    for i in range(999):
`range(999)` даст 999 элементов, а данных по заданию должно быть 1000 строк

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +            for i in range(999):
`range(999)` даст 999 элементов, а данных по заданию должно быть 1000 строк

2022-10-25 10:50 UTC, alxmcs commented on Lab2/random_of_copy.py
> +def create_copy_dataset_with_random_number(obj: object) -> None:
Конкретизировать тип объекта в тайп хинте.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/random_of_copy.py
> +
Пустая строка.

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +            for i in range(999):
`range(999)` даст 999 элементов, а данных по заданию должно быть 1000 строк

2022-10-25 10:50 UTC, alxmcs commented on Lab2/main.py
> +    def get_data_path_w2(self, data) -> list:
Нерепрезентативное название, функционал аналогичен `get_data_path` и `get_data_path_w`. Всю эту обработку можно __и нужно__ уместить в единственном методе.

2022-10-27 12:38 UTC, alxmcs commented on Lab2/iterator_class.py
> +if __name__ == "__main__":
Написание юнит тестов опционально - тебе еще 52 других замечания по коду править.

2022-10-28 08:44 UTC, Santas7 commented
я мог конечно что то упустить...

2022-10-29 10:28 UTC, alxmcs reviewed
Общие замечания:
1) Прочти, наконец, документацию к [os.path.join](https://docs.python.org/3/library/os.path.html), чтобы в следующей версии кода я не видел ни единого слеша в путях в твоих скриптах.
2) С версии 3.5.9 в python есть [перечисления](https://docs.python.org/3.10/library/enum.html), но ознакомиться с тем, как с ними работать, ты не соизволил. В место этого в коде та же самая параша, только с переименованной переменной.
3) Касательно секции кода с разбором строки в `next_element.py' я тоже писал в прошлом ревью. Ты делаешь то, что сто лет назад реализовано (и реализовано явно лучше). В предыдущем ревью я уже писал, что делать и куда для этого смотреть.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/main.py
> +            if enum == 0:
То есть ты просто переименовал переменную `id` в переменную `enum` и это типа должно было меня устроить?  Серьезно?

2022-10-29 10:28 UTC, alxmcs commented on Lab2/main.py
> +            if enum == 0:
Аналогично.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/main.py
> +            if enum == 0:
Аналогично.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/copy_elements.py
> +        os.rename(f'{later_dir}/{obj.class_name}/{i + 1:04d}.jpg',
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/copy_elements.py
> +                  f'{later_dir}/{obj.class_name}/{obj.class_name}_{i + 1:04d}.jpg')
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/copy_elements.py
> +        shutil.copy(os.path.join(f'{later_dir}/{obj.class_name}/{obj.class_name}_{(i + 1):04d}.jpg'),
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/copy_elements.py
> +        os.rename(f'{later_dir}/{obj.class_name}/{obj.class_name}_{i + 1:04d}.jpg',
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/copy_elements.py
> +                  f'{later_dir}/{obj.class_name}/{i + 1:04d}.jpg')
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/main.py
> +            with open(f'{self.dir_name}/annotation.csv', 'a', newline='') as file:
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/next_element.py
> +    with open(f'{obj.dir_name}/annotation.csv', 'r', newline='') as file:
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/random_of_copy.py
> +        os.rename(f'{later_dir}/{obj.class_name}/{i + 1:04d}.jpg',
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/random_of_copy.py
> +                  f'{later_dir}/{obj.class_name}/{n:05d}.jpg')
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/random_of_copy.py
> +        os.rename(f'{later_dir}/{obj.class_name}/{n:05d}.jpg',
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/random_of_copy.py
> +        shutil.copy(os.path.join(f'{later_dir}/{obj.class_name}/{n:05d}.jpg'), obj.dir_name)
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/random_of_copy.py
> +                  f'{later_dir}/{obj.class_name}/{i + 1:04d}.jpg')
Конкатенация путей только до сих пор не через `os.path.join`.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/next_element.py
> +        for i in range(len(tmp)):
Этот говеный кусок кода с ручным посимвольным разбором строки все еще на месте.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/random_of_copy.py
> +
Пустая строка все еще на месте.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/main.py
> +                file.close()
В предыдущем ревью я объяснял, почему эта строка не нужна, но она все еще на месте.

2022-10-29 10:28 UTC, alxmcs commented on Lab2/random_of_copy.py
> +
Пустая строка все еще висит.

2022-11-04 09:14 UTC, alxmcs approved these changes

2022-11-04 09:14 UTC, closed without merging