6213 Теребилкин Даниил Игоревич Лаб.1 Вар.9
itsecd/python pull request #17
Opened 2023-10-18 15:26 UTC by Quyntrd

В данной лабораторной работе от меня требовалось получить отзывы с сайта otzovik.com, создать dataset, в котором будет 5 папок с отзывами определенного рейтинга. Однако у меня возникла проблема, написав код, я начал его тестировать, выдавало ошибку TimeoutError, я нашел ошибку, из-за которой у меня могла она возникать(просто url не вставлялся так, как я хотел), но после этого меня перестало пускать на сайт с любого устройства, я попытался поменять свой Headers на более простой, но ошибка также выходит и не дает зайти на сайт.

2023-10-19 08:43 UTC, alxmcs requested changes
Касательно таймаутов в запросах. Да, у меня тоже не получилось ограбить отзовик. Предлагаю поискать другой ресурс с отзывами

![image](https://github.com/itsecd/python/assets/70561974/a9688925-9940-4a13-a299-8980c341131a)
![image](https://github.com/itsecd/python/assets/70561974/d75d65ec-4487-48a0-8e0a-fea69a96f159)

2023-10-19 08:43 UTC, alxmcs commented on Lab1/main.py
> +def w_review_to_txt_file(dataset_name: str, link: str, n_of_reviews:int)-> dict[str, int]:
Это не самое удачное именование функции

2023-10-19 08:43 UTC, alxmcs commented on Lab1/main.py
> +def w_review_to_txt_file(dataset_name: str, link: str, n_of_reviews:int)-> dict[str, int]:
И `n_of_reviews` тоже. Какое-нибудь `review_count` удобнее в восприятии

2023-10-20 16:22 UTC, Quyntrd commented
Поменял сайт для отзывов, поменял название функций и переменных, также вытащил из основной функции часть программы в другую функцию, чтобы выглядело чуть получше. Также добавил проверку на существование файла в директорию, чтобы он не скачивал один и тот же файл по несколько раз

2023-10-21 07:53 UTC, alxmcs requested changes

2023-10-21 07:53 UTC, alxmcs commented on .vscode/launch.json
Служебный файл ide убрать из репозитория

2023-10-21 07:53 UTC, alxmcs commented on Lab1/main.py
> +        review_links.append(f"{"https://www.banki.ru"}{link.find('a').get('href')}")
Думаю, имеет смысл изменить константу `BASE_URL` так, чтобы она действительно была базовой, и тебе не приходилось хардкодить домен в функциях

2023-10-21 07:53 UTC, alxmcs commented on Lab1/main.py
> +    rate_folder = os.path.join(dataset_name, f'{rating}').replace("\\","/")
В очередном pr подряд я вижу, как студенты руками переворачивают слеши в путях. Как только я указываю на это в коде, реплейс слешей просто убирают. А я очень хочу знать, зачем это делать. Чисто из эстетических соображений?

2023-10-21 07:53 UTC, alxmcs commented on Lab1/main.py
> +            if not os.path.exists(os.path.join(os.path.join(dataset_name, f'{rating}').replace("\\","/"), f"{count:04}.txt")):
Аналогично

2023-10-21 07:53 UTC, alxmcs commented on Lab1/main.py
> +    parser = argparse.ArgumentParser(description='Input path name for reviews, link for parsing, count of reviews')
Тут было бы неплохо указать, что софт заточен под работу с банками.ру

2023-10-21 07:53 UTC, alxmcs commented on Lab1/main.py
> +                if count % 25 == 0:
Тут было бы неплохо выдать некоторый прогресс скачивания рецензий пользователю, чтобы он не смотрел в пустой экран, пока софт работает

2023-10-21 07:53 UTC, alxmcs commented on Lab1/main.py
> +                            if count >= review_count:
Эту чудо конструкцию я тоже вижу не в первом pr.
У тебя же уже цикл `while count < review_count`
Но ты в каждой итерации заставляешь итератор чекать на count >= review_count. Это крайне неэффективно, а если вспомнить о том, что python в целом с циклами не дружит, то и негуманно

2023-10-21 07:53 UTC, alxmcs commented on Lab1/main.py
Давай назовем модуль как-нибудь иначе. Чтобы его функционал был ясен из названия. То, что он мейн и так ясно - он в директории один

2023-10-21 07:55 UTC, alxmcs commented
На будущее - если все необходимые изменения внесены, то ![image](https://github.com/itsecd/python/assets/70561974/3e4c4243-6f7e-450c-bb46-275476d1e168)

2023-10-22 08:06 UTC, Quyntrd commented
Пересмотрел BASE_URL. 
По поводу replace: когда код выполняется, путь для файлов в дебаге выглядел с //, и я считал, что это может вызвать ошибку, но как оказалось ничего подобного. 
Удалил переменную review_test, в review добавил метод .strip, чтобы в файл сохранялся текст без \n. 
Насчет count >= review_count - проблема в том, что если этой проверки не будет, то проверка в while не сработает пока работает цикл for, и тогда скачается больше файлов чем review_count.
Также в review была проблема, что сюда могла сохраниться строка заглушка. И как оказалось, что некоторые отзывы были написаны с использование <p> , а некоторые без, поэтому это тоже пришлось пересмотреть. Но проблема с необходимостью проверки мусорных отзывов отпала. 
Еще переделал проверку на существование отзыва в директории, потому что до этого если не существовал, допустим, первый файл, то он скачивал по новой все первые 25 отзывов, также если был первый, но не было второго, то первый и второй отзыв были одинаковыми, теперь код работает чуть дольше из-за того, что он проверяет существование после того как декодирует страницу, но все же это намного быстрее, чем скачивать все по новой, и теперь не будет такого, что отзывы будут повторяться при прерывании программы.

2023-10-22 09:29 UTC, alxmcs requested changes
Осталось привести в порядок bumpy road в функции `review_file`

2023-10-22 09:29 UTC, alxmcs commented on Lab1/banki_review_parser.py
> +                if count == review_count:
Опять то же самое - цикл `while count < review_count:` и так завершится при этом условии. Если смысл этой проверки - просто не выводить сообщение в логгинг, которое идет после него, на последней итерации цикла, то:
1) оно того не стоит,
2) это можно реализовать без увеличения цикломатической сложности кода.

2023-10-22 09:29 UTC, alxmcs commented on Lab1/banki_review_parser.py
> +                        page += 1
Ты уверен, что увеличивать индекс таблицы нужно в том случае, когда 
* файл с ревью с именем count уже существует,
* count +1 делится на 25 без остатка?
Мне такое специфическое условие кажется весьма сомнительным.
С учетом того, что на 77 строке ты и так инкрементируешь страницу

2023-10-22 15:33 UTC, alxmcs approved these changes

2023-11-16 07:03 UTC, closed without merging