6213 Шестериков Борис Владимирович Лаб. 2 Вар. 4
itsecd/python pull request #21
Opened 2023-10-20 12:03 UTC by BarMan555

Написать скрипты для создания csv файлов и копирования скаченных картинок в определенном формате

2023-10-20 13:36 UTC, alxmcs requested changes
Общие замечания:
1) В условии лабораторной подразумевается, что датасеты будут лежать где-то в директории проекта, только это не дает права хардкодить к ним пути.
2) Никто не говорил о том, что файл с аннотацией лежит рядом с датасетом. Нужно предусмотреть возможность сохранить его по произвольному пути.
3) Я бы декомпозировал это безобразие так, чтобы:
   * появилась, во-первых, нормальная единственная точка входа в приложение,
   * появился общий класс (предок или интерфейс)-стратегия, отвечающий за формирование датасета,
   * появились 3 его конкретные реализации, отвечающие каждый за свой вариант реализации вида формирования датасета,
   * появился класс-контекст, который бы выбирал определенную реализацию стратегии в зависимости от выбора пользователя (да, опять argparse/dotenv/json и так далее),
4) Класс для итерации по датасету - это то, что будет тебе необходимо для реализации 3 лабы. Он будет использоваться для переключения картинок в окошке гуйни. Он не должен использоваться для создания аннотаций, он потребляет аннотации. Это результат этой лабораторной, а не инструмент для ее реализации.
При этом, тебе надо итерировать не просто по датасету, а по по классам из датасета.
Соответственно, итоговый класс для итерации по датасету будет композицией двух экземляров кастомного итератора, который ты реализовал.

Основная сложность 2 лабы - сесть и проанализировать бизнес-требования (которые, если быть честным, довольно говено изложены в методичке, но это совсем другая история) перед имплементацией. К счастью для тебя, в этом ревью я все за тебя проанализировал (за исключением мелочей типа где и как лучше реализовать метод, который будет записывать поля аннотации в csv и т.д.). Тебе осталось только реализовать.

2023-10-20 13:36 UTC, alxmcs commented on Lab2/script_3.py
> +            iterator = Iterator(f'Lab2/{sj["normal"]}.csv', img_class)
А завязывать реализацию одного типа генерации датасета на итератор, который использует готовый датасет другого типа - вообще что-то за гранью добра и зла

2023-10-25 18:31 UTC, BarMan555 commented
Вторая лаба находится в папке app

2023-10-31 07:28 UTC, alxmcs requested changes
Общее:
* `make_normal`,`make_random`,`make_together` содержат практически идентичный код. На мой взгляд, было бы логичнее соорудить единственную функцию с дополнительным параметром (например, енамом), который отвечал бы за тип обработки датасета.
* Может быть, стоит внести папку `app` под `Lab2`? В следующих лабах тоже придется делать некоторые приложения, так что они тоже в каком-то роде имеют право жить в `app`

2023-10-31 07:28 UTC, alxmcs commented on app/get_way.py
> +    return os.path.join(json_unpack()[0], f"{object}/{number:04}.jpg")
А вот тут, пожалуй, можно было `os.path.join(json_unpack()[0], object, f"{number:04}.jpg")`

2023-10-31 07:28 UTC, alxmcs commented on app/iterator.py
> +class CsvIterator:
Этот итератор выдает следующую строку из csv. А нужно выдавать путь к следующему изображению определенного типа.

2023-10-31 07:28 UTC, alxmcs commented on app/get_way.py
> +        name = json.load(name_json)
1) Не слишком ли много настроечных файлов для одного приложения? Мб проявить жалость к пользователю и не заставлять его вносить настройки в сразу три файла, а ограничиться единственным?
Если есть желание сгруппировать настройки по категориям, то всегда можно сделать так:
```json
{
"names":
     {  
          "name-normal" : "dataset", 
          "name-together" : "dataset_together", 
          "name-random" : "dataset_random"
     },
"settings":
    {
        "mode" : "random",
        "objects" : ["rose", "tulip"]
    },
"src":
    {
        "name-dir" : "app",
        "name-csv-dir" : "csv",
        "name-data-dir" : "data",
        "name-json-dir" : "json",
       "name-images-dir" : "Lab1/dataset"
    }
}
```

2) В этих настройках черт ногу сломит, они все называются практически идентично.

2023-10-31 07:28 UTC, alxmcs commented on app/main.py
> +        make_random.make_new_fold(os.path.join(src["name-dir"], src["name-csv-dir"], name["name-random"]), setting["objects"], src["name-images-dir"])
Думаю, имеет смысл вынести обработку разных режимов в отдельные функции, чтобы как-то разгрузить эти строки длинной в километр

2023-10-31 07:28 UTC, alxmcs commented on app/usefull_functions.py
Они `useful`, если ты манипулируешь с csv. Может быть, имеет смысл переименовать модуль так, чтобы фигурировало csv в его названии?

2023-10-31 13:41 UTC, alxmcs approved these changes

2023-11-16 07:02 UTC, closed without merging