6213 Будюк В.А. Лаб.2 Вар.4
itsecd/python pull request #22
Opened 2023-10-22 15:34 UTC by Nibuku

2023-10-23 12:58 UTC, alxmcs requested changes
Общие замечания:
* Это явно не по РЕР.
![image](https://github.com/itsecd/python/assets/70561974/4628e58a-afa0-4ddd-9b5b-95787bca4bd5)

* Хотелось бы увидеть в приложении одну точку входа, при помощи которой пользователь мог бы создать аннотацию выбранного им типа.

* В #21 я уже привел пример, как можно относительно красиво реализовать эту лабораторную, используя паттерны проектирования. Не настаиваю на нем, но б это поможет тебе привести твой код в порядок.

2023-10-23 12:58 UTC, alxmcs commented on Lab2/iterator.py
Результатом этой лабораторной должен стать класс, который после будет импортирован в 3 лабу. Класс должен уметь выдавать путь к следующему изображению выбранного типа. Текущий итератор работает только с одной фиксированной меткой класса. Соответственно, тебе нужно соорудить класс, который держал бы внутри два итератора и имел бы метод, который выдавал бы корректный путь до следующего изображения в зависимости от входной метки класса.

2023-10-23 12:58 UTC, alxmcs commented on Lab2/script2.py
> +def download_in_new_directory(
`download_in_new_directory` и ` download_with_random` содержат практически идентичный код. Может быть, стоит объединить их в одну функцию?

2023-10-23 12:58 UTC, alxmcs commented on Lab2/script4.py
> +def get_path(path: str, file_name: str) -> str:
Какой смысл было имплементировать эту функцию, если ты нигде ей в коде не пользуешься?

2023-10-23 12:58 UTC, alxmcs commented on Lab2/iterator.py
> +    def __next__(self) -> str:
Было бы неплохо написать для итератора какой-нибудь код под `if __name__ == "__main__':`, где можно было бы проверить его работоспособность (раз о юнит-тестах вы узнаете только на следующем курсе)

2023-10-27 14:14 UTC, alxmcs requested changes

2023-10-27 14:14 UTC, alxmcs commented on Lab2/iterator.py
> +class ClassesIterator(ElementIterator):
Какой смысл оборачивать вокруг `ElementIterator` еще один класс, который никаким образом не развивает функционал? 
Для 3 лабы нужно итерировать по 2 классам, так почему бы в рамках `ClassesIterator` не реализовать итерирование по обоим классам в одном методе, сделав этот класс композицией двух экземпляров`ElementIterator`?
Как-нибудь так:
```py
class ClassesIterator:

   def __init__(self, path, first_class, second_class):
      self.__first_class = first_class
      self.__second_class = second_class
      self.__first_iterator = ElementIterator(path, first_class)
      self.__second_iterator = ElementIterator(path, second_class)

   def next(self, class_name):
      if class_name == self.__first_class:
         return next(self.__first_iterator)
      if class_name == self.__second_class:
         return next(self.__second_iterator)
     raise Exception('Wrong class name')

iter = ClassesIterator("Lab2\csv_files\datasets.csv", "rose", "tuplip")
next_rose_path = iter.next("rose")
next_tulip_path = iter.next("tuplip")
```
Или так:
```py
class ClassesIterator:

   def __init__(self, path, first_class, second_class):
      self.__first_iterator = ElementIterator(path, first_class)
      self.__second_iterator = ElementIterator(path, second_class)

   def next_first(self):
      return next(self.__first_iterator)

   def next_second(self):
      return next(self.__second_iterator)

iter = ClassesIterator("Lab2\csv_files\datasets.csv", "rose", "tuplip")
next_rose_path = iter.next_first()
next_tulip_path = iter.next_second()
```

2023-10-27 14:14 UTC, alxmcs commented on Lab2/iterator.py
> +    print(mi.__next__())
Мб все-таки обойтись без принтов?

2023-10-27 14:14 UTC, alxmcs commented on Lab2/main.py
> +    )
Мы, вроде, договаривались, что с пользователем взаимодействуем через argparse/dotenv/json, но откуда то появился инпут с консоли.

2023-10-27 14:14 UTC, alxmcs commented on Lab2/main.py
> +        settings = json.load(settings)
От 1 лабораторной здесь нужны только данные. Тащить оттуда настройки не стоит, лучше обойтись автономным для каждого приложения файлом настроек

2023-10-27 14:14 UTC, alxmcs commented on Lab2/random_of_copy.py
> +            numbers.add(random.randint(0, 10000))
А что если генератор случайных чисел выдаст случайное число, которое уже выдавал ранее?

2023-10-27 18:50 UTC, Nibuku commented on Lab2/random_of_copy.py
> +            numbers.add(random.randint(0, 10000))
Извините, вероятно я не права, но логика там была следующая: 
в 18 строке создается множество numbers и заполняется рандомными значениями, пока длина множества не будет равна общему количеству файлов в датасете. Затем преобразовываю множество в список, чтобы работать с элементами по индексу

2023-10-30 08:23 UTC, alxmcs commented on Lab2/random_of_copy.py
> +            numbers.add(random.randint(0, 10000))
А, да, действительно, там `set()`
![image](https://github.com/itsecd/python/assets/70561974/d0158747-7f4b-480a-bf9f-c4d5a5f536d8)

2023-10-30 08:37 UTC, alxmcs requested changes
Осталось поправить буквально один момент

2023-10-30 08:37 UTC, alxmcs commented on Lab2/main.py
> +mode = input()
На текущий момент у тебя используется 2 файла с настройками, из которых ты используешь следующие поля:
```json
{   
    "classes": ["rose","tulip"], 
    "main_folder":"dataset",
    "directory": "Lab2",
    "folder": "csv_files",
    "normal": "datasets",
    "new_name": "dataset_new",
    "random": "dataset_random"
}
```
Очевидные проблемы тут:
* нет смысла раскидывать настройки на два файла,
* один из используемых файлов - это настройки совершенного другого абсолютно несвязанного с этим приложения  (1 лаба),
* файл настроек из 1 лабы, который ты переиспользуешь тут, содержит набор настроек, который тебе тут не нужен - урл поисковика, число страниц, число картинок,
* имена полей настроек максимально похожи друг на друга,
* некоторые из этих настроек мне кажутся избыточными.

Соответственно, предлагаю поместить все необходимые настройки для работы 2 лабы в одни файл в директории 2 лабы.

Также было бы гуманно поместить в этот файл режим работы для аннотатора, который ты заставляешь сейчас пользователя вводить в консоли:
```json
"mode": "random",
```

Сейчас, чтобы запустить твое приложение пользователю нужно:
* ввести параметры в файл настроек в директории другого проекта,
* ввести параметры в файл настроек в директории этого проекта,
* ввести в консоль режим работы софта.

После изменений, которые я предлагаю внести, пользователю достаточно будет сделать следующее:
* ввести параметры в файл настроек в директории этого проекта.

Что гораздо удобнее и совсем не является преступлением против человечества.

2023-10-30 08:39 UTC, alxmcs approved these changes
Нет, не осталось, я смотрел в старую версию кода

2023-11-16 07:02 UTC, closed without merging