Панюшкин Андрей 6213, Л/Р №3, вариант 4
itsecd/python pull request #22
Opened 2022-11-06 09:23 UTC by Santas7

В данной лабораторной работе я создал файл main_window.py в котором сделал класс MainWindow - основное окно программы. Я реализовал графический интерфейс для взаимодействия с методами и функциями из 2-й лабы.

**Основные методы класса MainWindow**:
    1. next_rose() - следующая картинка rose
    2. next_tulip() - следующая картинка tulip
    3. back_rose() - предыдущая картинка rose
    4. back_tulip() - предыдущая картинка tulip
    5. create_annotation() - создать аннотацию
    6. copy_of_dataset(self) - создать копию датасет
    7. random_of_dataset(self) - рандом-я датасет
    8. exit() - выход из программы

2022-11-07 13:21 UTC, alxmcs requested changes
Общие замечания:
1) Текстбокс с путем к датасету обрезает путь, это заметно даже на скриншоте.
2) Я бы хотел видеть в качестве лейаута адаптивный грид, который резайзился бы под размер просматриваемого изображения, с возможностью развернуть окно на полный экран. В данный момент окно приложения залочено и менять его размеры никак нельзя.

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +from PyQt6.QtGui import QPixmap
этот импорт не используется

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +from PyQt6.QtWidgets import QApplication, QMainWindow, QPushButton, QLabel, QFileDialog, QVBoxLayout, QHBoxLayout, \
`QVBoxLayout, QHBoxLayout` тоже не используются

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +from PyQt6.QtCore import QSize, Qt
`Qt` не используется

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +        self.s_p_rose = f"dataset\\{annotation.CLASS_DEFAULT[0]}\\0001.jpg"  # начальный для rose
конкатенация путей через `os.path.join`

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +        self.s_p_tulip = f"dataset\\{annotation.CLASS_DEFAULT[1]}\\0001.jpg"  # начальный для tulip
конкатенация путей через `os.path.join`

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +                self.s_p_rose = f"dataset\\{annotation.CLASS_DEFAULT[0]}\\0001.jpg"
конкатенация путей через `os.path.join`

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +                self.s_p_tulip = f"dataset\\{annotation.CLASS_DEFAULT[1]}\\0001.jpg"
конкатенация путей через `os.path.join`

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +                self.s_p_tulip = f"dataset\\{annotation.CLASS_DEFAULT[1]}\\0001.jpg"
конкатенация путей через `os.path.join`

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +    def next_rose(self):
смысл реализовывать по два метода для одних и тех же действий (`next_rose`,`next_tulip`), если можно написать единственный, где выбор класса изображения будет параметризирован?

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +    def next_tulip(self):
смысл реализовывать по два метода для одних и тех же действий (`next_rose`,`next_tulip`), если можно написать единственный, где выбор класса изображения будет параметризирован?

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +    def back_rose(self):
смысл реализовывать по два метода для одних и тех же действий (`back_rose`,`back_tulip`), если можно написать единственный, где выбор класса изображения будет параметризирован?

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +    def back_tulip(self):
смысл реализовывать по два метода для одних и тех же действий (`back_rose`,`back_tulip`), если можно написать единственный, где выбор класса изображения будет параметризирован?

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +        self.s_p_rose = f"dataset\\{annotation.CLASS_DEFAULT[0]}\\0001.jpg"  # начальный для rose
а что если в директории, изображения которой ты собрался визуализировать, не будет изображения `0001.jpg`? (к примеру, при просмотре датасета, названия файлов которого ты рандомизировал)

такие данные надо не хардкодить, а получать из анализа выбранной пользователем директории

2022-11-07 13:21 UTC, alxmcs commented on Lab3/main_window.py
> +        self.s_p_tulip = f"dataset\\{annotation.CLASS_DEFAULT[1]}\\0001.jpg"  # начальный для tulip
аналогично

2022-11-07 13:28 UTC, alxmcs commented
Еще хотелось бы название для приложения повменяемее, чем "MyApp"

2022-11-07 15:41 UTC, Santas7 commented
поправил код)

2022-11-08 08:38 UTC, alxmcs approved these changes
Ого, это что, енамы

2022-11-08 08:38 UTC, closed without merging