Lab2 var5
itsecd/python pull request #24
Opened 2023-10-30 01:01 UTC by Nakamo312

Короче, я жестко накосячил с веткой, мне пришлось ее удалить со всеми коммитами и создать новую, потому коммит только один, но там я попытался описать примерную последовательность изменений

2023-10-30 01:18 UTC, Nakamo312 reviewed
я не знаю почему папки "__pycache__" добавляются в список отслеживаемых, хотя в .gitignore они помечены

2023-10-30 08:12 UTC, alxmcs requested changes

2023-10-30 08:12 UTC, alxmcs commented on Lab2/write_to_csv.py
> +from Lab2.src.write_reader import *
Аналогично

2023-10-30 08:12 UTC, alxmcs commented on Lab2/src/write_reader.py
> +            # iterate over data dicts and write values
Думаю, инлайн-комментарии тут излишни - докстринг у метода есть, да и сами операции очевидные

2023-10-30 08:12 UTC, alxmcs commented on Lab2/src/write_reader.py
> +            logging.error('A folder with the same name already exists')
Проглочен объект исключения, лучше вывести его поля в логе

2023-10-30 08:12 UTC, alxmcs commented on Lab2/src/write_reader.py
> +            logging.error(f"Directory '{main_dir}' does not exist")
Проглочен объект исключения, лучше вывести его поля в логе

2023-10-30 08:12 UTC, alxmcs commented on Lab2/src/write_reader.py
> +            logging.error(f"CSV '{path}' does not exist")
Проглочен объект исключения, лучше вывести его поля в логе

2023-10-30 08:12 UTC, alxmcs commented on Lab2/src/write_reader.py
> +class ClassInstanceIterator:
Лучше разделить `ClassInstanceIterator` и `DataWriteReader` по разным модулям, они имеют достаточно различный функционал и совершенно автономны друг от друга. Более того, `DataWriteReader` в 3 лабе уже не пригодится

2023-10-30 09:04 UTC, Nakamo312 commented on Lab2/src/write_reader.py
> +class ClassInstanceIterator:
![image](https://github.com/itsecd/python/assets/120848604/2dd96988-009b-4686-920a-48be8f21d423)

2023-10-30 09:34 UTC, Nakamo312 commented on Lab2/src/write_reader.py
> +class ClassInstanceIterator:
![image](https://github.com/itsecd/python/assets/120848604/aba0085c-343f-4a3e-ba55-8826af09ce69)
Мне показалось что логика приложения должна быть такой. Ну еще кнопки для итераций по выбранному классу добавить

2023-10-30 14:51 UTC, alxmcs commented on Lab2/src/write_reader.py
> +class ClassInstanceIterator:
Ладно, поймал старика на приступе деменции, создание аннотаций все-таки пригодится

2023-10-30 14:55 UTC, alxmcs requested changes
Ты точно планировал сдавать 2 и 3 лабу за один pr? Или не сменил ветку для последующих коммитов?

2023-10-30 14:55 UTC, alxmcs commented on Lab3/gui.py
> +    def set_appears(self):
Не забываем про РЕРы

2023-10-30 14:55 UTC, alxmcs commented on Lab3/gui.py
> +    def initUI(self):
И тут тоже

2023-10-30 14:55 UTC, alxmcs commented on Lab3/gui.py
> +
Зато тут пустых строк полно

2023-10-30 14:55 UTC, alxmcs commented on Lab3/gui.py
> +
И здесь

2023-10-30 14:55 UTC, alxmcs commented on Lab3/write_reader.py
Зачем тащить судя исходник из 2 лабы, если его можно проимпортировать?

2023-10-30 18:37 UTC, Nakamo312 commented
> Ты точно планировал сдавать 2 и 3 лабу за один pr? Или не сменил ветку для последующих коммитов?

нет. я точно не планировал, а зашел в репозиторий и забыл что переключался на lab-2-var5, потом решил исправить ошибки второй лабы, но перед эти нужно сделать коммит 3 лабы чтоб не потерять изменения при переключении, и вышло так что нечайно коммит попал во вторую ветку

2023-10-31 07:31 UTC, alxmcs commented
В таком случае, предлагаю заревертить коммиты из этой ветки (или черри-пикнуть их в нужную ветку), чтобы в этом 
 pr осталась только 2 лаба.

2023-10-31 11:01 UTC, Nakamo312 commented
папку 'Lab1" пробовал скрыть и через  git filter-branch --tree-filter "rm -rf Lab1" HEAD 
 и через git rm Lab1. Подскажите пожалуйста как это правильно сделать, из истории коммитов не нашел в принципе где эта директория появляется

2023-10-31 13:33 UTC, alxmcs approved these changes

2023-11-16 07:01 UTC, closed without merging