6213-100503D Корся Ева Дмитриевна лаб 2, вар 9
itsecd/python pull request #25
Opened 2023-11-13 12:01 UTC by IvaKorsya

написать 5 скриптов, из которых первые три создают аннотации к dataset в различных его видах согласно заданию. 4 скрипт это получение следующего элемента конкретного класса, а 5 - итератор для удобного перемещения по отзывам.

первые три скрипта в последствии были объединены в файл annotation.py  для удобного подключения и использования в файле path_to_next.py.

2023-11-13 12:03 UTC, IvaKorsya commented
первые три скрипта в последствии были объединены в файл annotation.py для удобного подключения и использования в файле path_to_next.py.

2023-11-13 12:21 UTC, alxmcs requested changes
В модулях присутствует дублирование кода - куча функций с одинаковыми названиями и одинаковым кодом (или слегка разными названиями и слегка разным кодом).

2023-11-13 12:21 UTC, alxmcs commented on Lab2/annotation.py
> +    else:
Сделать через [enum](https://docs.python.org/3/library/enum.html)

2023-11-13 12:21 UTC, alxmcs commented on Lab2/path_of_next.py
> +def get_path_of_next(class_label: int, ind: int, csv_path='reviews.csv'):
Зачем было писать эту функцию, если в итераторе она никак не применяется?

2023-11-13 12:21 UTC, alxmcs commented on Lab2/annotation_w_copy.py
> +def write_csv(path='new_reviews.csv') -> None:
Зачем дублировать код? Эта функция присутствует тут

2023-11-13 12:21 UTC, alxmcs commented on Lab2/annotation_w_rand.py
> +def write_csv(path='new_reviews_w_rand_num.csv') -> None:
И тут

2023-11-13 12:21 UTC, alxmcs commented on Lab2/annotation.py
> +def write_csv(path_to_csv='reviews.csv', label_of_annotation=0, new_dir='new_dataset', old_dir='dataset') -> str:
И в более продвинутом виде тут. Зачем?

2023-11-13 12:21 UTC, alxmcs commented on Lab2/annotation.py
> +def get_annotation(dir='dataset') -> Generator[list, None, None]:
Эту функцию

2023-11-13 12:21 UTC, alxmcs commented on Lab2/annotation.py
> +def get_annotation_new_dir(old_dir='dataset', new_dir='new_dataset') -> Generator[list, None, None]:
И эту функцию можно параметризовать и объединить в одну, чтобы не дублировать код

2023-11-13 12:21 UTC, alxmcs commented on Lab2/annotation.py
> +def copy_with_rand_num(old_dir='dataset', new_dir='dataset_with_rand_num') -> Generator[list, None, None]:
Здесь

2023-11-13 12:21 UTC, alxmcs commented on Lab2/annotation.py
> +def copy_to_dir(old_dir='dataset', new_dir='new_dataset'):
И здесь аналогично

2023-11-13 12:21 UTC, alxmcs commented on Lab2/annotation.py
> +def mkdir(path: str) -> None:
Лучше не именовать функции так же, как и функции стандартных библиотек

2023-11-13 13:03 UTC, IvaKorsya commented
там итоговые только три файла я просто забыла удалить с гитхаба annotation_w_copy.py и annotation_w_rand.py
остальное сейчас исправлю

2023-11-14 07:03 UTC, alxmcs approved these changes

2023-11-16 07:00 UTC, closed without merging