Lab1var8
itsecd/python pull request #37
Opened 2023-11-16 17:07 UTC by bonyfa

2023-11-17 10:08 UTC, alxmcs requested changes
Общее замечание - и кому я в итоге должен эту лабу зачесть?  ![image](https://github.com/itsecd/python/assets/70561974/54ecefba-3a20-4d65-8153-beddb3d0c68d)

2023-11-17 10:08 UTC, alxmcs commented on lab111.py
> +                        number += 1
Это кусок бизнес-логики приложения, он не должен исполняться под `if __name__ == "__main__":`

2023-11-17 10:08 UTC, alxmcs commented on lab111.py
> +        print("Было успешно сохранено", number ,"рецензий")
Должно быть через `logging`

2023-11-24 00:11 UTC, bonyfa commented
Сулейманян Арсен Владимирович 6213

2023-11-24 09:26 UTC, alxmcs commented
> Сулейманян Арсен Владимирович 6213

Класс, теперь впиши это в название pr

2023-11-24 09:45 UTC, alxmcs requested changes
Общие замечания: 
* Репозиторий - место для хранения исходного кода. Место для хранения данных - это бд, бакеты, дататоры и т.д. В репозитории им не место.
* Проигнорирована половина замечаний с прошлого ревью. Ты серьезно рассчитывал, что я это не замечу? Тут все задокументировано в письменном виде.

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
>Название модуля не соответствует РЕР

Все еще не соответствует

Соврал, получается:
![image](https://github.com/itsecd/python/assets/70561974/22118d0a-ac90-41d1-a75a-0939aae5a124)

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +def get_html_code(page: int , url: str) -> BeautifulSoup:
>Нет докстринга

Все еще нет докстринга

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +def get_reviews(soup: BeautifulSoup) -> List[BeautifulSoup]:
>Нет докстринга

Все еще нет докстринга

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +def review_text(review: BeautifulSoup) -> str:
>Нет докстринга

Все еще нет докстринга

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +def get_name(soup:BeautifulSoup) -> str:
>Нет докстринга

Все еще нет докстринга

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +def status_review(review: BeautifulSoup) -> bool:
>Нет докстринга

Все еще нет докстринга

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +def random_user_agent() -> str:
>Нет докстринга

Все еще нет докстринга

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +def create_directories():
>Нет докстринга

Все еще нет докстринга

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +        for folder_name in ["good", "bad"]:
>Захардкожено множество значений имени директории

Все еще захардкожено

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +            folder_path = os.path.join("dataset", folder_name)
> Захардкожена часть пути до директории

Все еще захардкожена

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +        folder_name = "good"
>Захардкожено имя директории

Все еще захардкожено

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +        folder_name = "bad"
>Захардкожено имя директории

Все еще захардкожено

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +def parsing_review():
Нет тайпхинтов, нет докстринга

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +        args = parse_arguments()
Получать параметры из командной строки внутри метода - плохая идея. Если кто-то решить импортировать твой модуль в свой проект, он будет ограничен в возможности применения этой функции.

2023-11-24 09:45 UTC, alxmcs commented on lab111.py
> +def parse_arguments():
Против группировки парсинга аргументов в виде функции ничего не имею, но мне крайне не нравится ее использование в коде. 
Получи параметры под мейном, распакуй их и передай в нужную функцию. Не надо вызывать парсинг аргументов внутри функции с бизнес-логикой приложения.

2023-11-27 23:02 UTC, bonyfa commented on lab111.py
> +        folder_name = "bad"
Я немного не понял что именно захардкожено, не могу придумать как проще это сделать

2023-11-28 07:51 UTC, alxmcs requested changes
Я уже неоднократно писал, чтобы ты убрал данные из репозитория. Они все еще тут.

2023-11-28 07:51 UTC, alxmcs commented on lab111.py
> +        for folder_name in ["good", "bad"]:
Вынеси это уже в константы

2023-11-28 07:51 UTC, alxmcs commented on lab111.py
> +            folder_path = os.path.join("dataset", folder_name)
А общую директорию, куда сохранять датасет - в аргументы командной строки со значением по умолчанию

2023-11-28 07:51 UTC, alxmcs commented on lab111.py
> +        folder_name = "good"
Соответственно, все эти статусы ревью и имена папок тоже будут браться из констант

2023-11-28 07:51 UTC, alxmcs commented on lab111.py
> +    parsing_review(out_dir,urls,pages)
Да просто распакуй их в вызове функции
Зачем тебе эти три переменные, когда можно просто
```py
args = parse_arguments()
parsing_review(*args)
```

2023-11-28 07:51 UTC, alxmcs commented on lab111.py
Я все еще надеюсь и жду, что ты нормально назовешь этот модуль

2023-11-28 07:51 UTC, alxmcs commented on requirements.txt.txt
1) Файл пустой. У тебя точно код зависит только от стандартных библиотек?
2) Файл назван неверно

2023-11-28 20:49 UTC, bonyfa commented
Переместил функцию create_directories() в main так как мы нем получаем аргументы в которых есть общая директория для вывода dataset

2023-11-29 06:54 UTC, alxmcs requested changes
Я уже которое ревью подряд говорю: убери данные из репозитория. Эти 152 текстовых файла тут не нужны. Их тут не должно быть. Репозиторий - для кода, 152 текстовых файла - не код.

2023-11-29 06:54 UTC, alxmcs commented on Lab1/lab111.py
> +    итоговая функция которая используя все пердидущие функции  полностью выполняет задачу
>пердидущие

2023-11-29 06:54 UTC, alxmcs commented on Lab1/lab111.py
> +    parsing_review(args)
В предыдущем ревью я буквально показал тебе пример кода с распаковкой аргументов, но ты им не воспользовался.
В итоге в модуле несколько франкенштейнов которые принимают нераспакованные аргументы от argparse. Так делать нельзя.

2023-11-29 06:54 UTC, alxmcs commented on Lab1/lab111.py
> +def parsing_review(args:argparse):
Вернуть вменяемые аргументы, добавить тайпхинт возвращаемого значения

2023-11-29 06:54 UTC, alxmcs commented on Lab1/lab111.py
> +def save_review_to_file(review_text: str, status_review: bool, review_n_g: int, review_n_b: int):
Добавить тайпхинт возвращаемого значения

2023-11-29 06:54 UTC, alxmcs commented on Lab1/lab111.py
> +def create_directories(args:argparse):
Вернуть вменяемые аргументы, добавить тайпхинт возвращаемого значения

2023-11-29 13:43 UTC, bonyfa commented on Lab1/lab111.py
> +def parsing_review(args:argparse):
Так это функция ничего не возвращает

2023-11-29 13:47 UTC, bonyfa commented
Вроде поправил aргументы функции, и передал распакованные args, но не понял про тайпхинт возвращаемого значения если функции ничего не возвращают

2023-11-29 13:51 UTC, alxmcs commented
> не понял про тайпхинт возвращаемого значения если функции ничего не возвращают

Значит это `-> None`

2023-11-30 08:15 UTC, alxmcs commented on Lab1/lab111.py
> +def parse_arguments():
тут тоже `->None`

2023-12-01 06:34 UTC, alxmcs approved these changes

2023-12-14 07:59 UTC, closed without merging