Лаборатория №3 - вариант 3. Ле Хань Хоанг 6213
itsecd/python pull request #37
Opened 2022-11-25 17:48 UTC by vieKH

Для функций из 2 лабораторной было реализовано приложение с графическим интерфейсом.
При инициализации приложение запрашивает путь к папке с исходным датасетом.

2022-11-27 18:40 UTC, alxmcs requested changes
В окне программы изображение не отображается целиком:
![image](https://user-images.githubusercontent.com/70561974/204153446-a108d2d9-7ba7-4766-8b6e-33a8746ddff4.png)

Также элемент `image` не адаптируется к изменению размера окна программы:
![image](https://user-images.githubusercontent.com/70561974/204153489-3e9f64bb-5336-4f9a-8b1b-d539743e3a17.png)

2022-11-27 18:40 UTC, alxmcs commented on Lab3/window.py
> +        button_next_dog.clicked.connect(lambda label="dog", cur_iter=iterator_dog: self.next("dog", cur_iter))
параметр `label` в теле лямбда-функции никак не используется

2022-11-27 18:40 UTC, alxmcs commented on Lab3/window.py
> +        button_next_cat.clicked.connect(lambda label="cat", cur_iter=iterator_cat: self.next("cat", cur_iter))
параметр `label` в теле лямбда-функции никак не используется

2022-11-27 18:40 UTC, alxmcs commented on Lab3/window.py
> +        self.dataset_path = QFileDialog.getExistingDirectory(self, 'Выберите папку исходного датасета')
При такой работе кода у пользователя нет возможности сменить датасет, с которым он работает.
Лучше сделать кнопку, которая позволит пользователю выбрать директорию с датасетом для работы в любой момент работы с датасетом, а не ограничивать его единсвенным выбором папки при запуске программы.

2022-11-27 18:40 UTC, alxmcs commented on Lab3/window.py
> +        path_dog = os.path.join(self.dataset_path, "dog", "0000.jpg")
В общем случае, директория датасета может не иметь вложенных папок с именами класса и не иметь файла с именем 0000.jpg

2022-11-27 18:40 UTC, alxmcs commented on Lab3/window.py
> +        path_cat = os.path.join(self.dataset_path, "cat", "0000.jpg")
Аналогично предыдущему замечанию

2022-11-28 10:22 UTC, alxmcs commented
Касательно отображения изображений советую посмотреть документацию [тут](https://doc.qt.io/qt-6/qpixmap.html#scaled), [тут](https://doc.qt.io/qt-6/qpixmap.html#scaledToHeight) и [тут](https://doc.qt.io/qt-6/qpixmap.html#scaledToWidth).

2022-11-28 11:00 UTC, alxmcs requested changes

2022-11-28 11:24 UTC, alxmcs commented on Lab3/window.py
> +            pixmap = QtGui.QPixmap(cur_iter.__iter__())
Проблему с отображением не всей картинки можно решить примерно так:
```py
pixmap = QtGui.QPixmap(cur_iter.__iter__()).scaled(self.image.height(), self.image.width(), aspectRatioMode=Qt.AspectRatioMode.KeepAspectRatio)
```
Было:
![image](https://user-images.githubusercontent.com/70561974/204266055-728358ff-3d35-4025-a55b-3f86296f99c5.png)
Стало:
![image](https://user-images.githubusercontent.com/70561974/204265970-82079d7e-b931-4ea3-af7c-6e4109955a47.png)


```

2022-11-28 12:26 UTC, vieKH commented on Lab3/window.py
> +            pixmap = QtGui.QPixmap(cur_iter.__iter__())
Спасибо вам большое

2022-12-03 10:49 UTC, alxmcs requested changes
Осталось поправить некоторые мелочи

2022-12-03 10:49 UTC, alxmcs commented on Lab3/window.py
> +    def init_ui(self):
Поскольку сейчас изображение для просмотра ресайзится под размер элемента, который его показывает, я бы предложил зафиксировать размер окна программы

2022-12-04 07:22 UTC, alxmcs approved these changes

2022-12-04 07:22 UTC, closed without merging