6213 Будюк В.А. Лаб.3 Вар.4
itsecd/python pull request #38
Opened 2023-11-16 19:13 UTC by Nibuku

2023-11-17 08:47 UTC, alxmcs requested changes
Давай сначала разберемся с дублированием кода, а потом я посмотрю на лейаут получившегося приложения

2023-11-17 08:47 UTC, alxmcs commented on Lab3/csv_annotation.py
Зачем копировать код  из 2 лабы в 3, если можно его проимпортировать? (если затрудняешься импортировать код из папки соседнего проекта, то [вот](https://stackoverflow.com/questions/4383571/importing-files-from-different-folder?page=1&tab=scoredesc#tab-top))

2023-11-17 08:47 UTC, alxmcs commented on Lab3/iterator.py
Аналогично

2023-11-17 08:47 UTC, alxmcs commented on Lab3/new_name_copy.py
Аналогично

2023-11-17 08:47 UTC, alxmcs commented on Lab3/random_of_copy.py
Аналогично

2023-11-17 09:19 UTC, Nibuku commented on Lab3/csv_annotation.py
Большое спасибо! Потому что с импортом действительно возникли сложности, пробовала и через sys.path.append и через ..Lab2/путь к файлу и через консоль (python -m Lab3.main_window.py)

2023-11-17 14:11 UTC, alxmcs requested changes
Есть определённые проблемы с лейаутом:
![image](https://github.com/itsecd/python/assets/70561974/eb99d0f4-5219-4715-a0d7-05d2d36405c5)
![image](https://github.com/itsecd/python/assets/70561974/0238406d-8436-4168-9b13-64956690dcf5)

2023-11-17 14:11 UTC, alxmcs commented on Lab3/main_window.py
> +        self.go_to_exit = self.add_button("Выйти из программы", 150, 50)
С кнопками следующая проблема:
`Следующая роза-->` и `Следующий тюльпан-->` должны быть активны после успешного завершения файлдиалога в `Начать итерацию`. Однако, они активны всегда по дефолту. Если на них нажать до выбора аннотации, то приложение крашится. В таком случае, не стоит позволять пользователю так делать)

2023-11-17 14:11 UTC, alxmcs commented on Lab3/main_window.py
> +    QMainWindow,
`QMainWindow` уже импортировался - 6 строка

2023-11-17 14:11 UTC, alxmcs commented on Lab3/main_window.py
> +        )
Выбирать папку с датасетом для итерирования  по датасету нет необходимости - достаточно выбрать аннотацию. Так что не особенно честно заставлять пользователя каждый раз выбирать папку с датасетом

2023-11-21 06:06 UTC, alxmcs approved these changes
Думаю, в текущем виде код можно принять

2023-11-29 09:56 UTC, closed without merging