6213 Ксеневич Максим Lab 1 Var 10
itsecd/python pull request #41
Opened 2023-11-20 21:19 UTC by maeosha

нужно было запарсить сайт с книжными отзывами. Сложность была в том, что полный отзыв нужно достать, нажав на кнопку

2023-11-21 06:01 UTC, alxmcs requested changes
Гитхаб не вывозит в отображение 3904 файлов. Убери данные из репозитория, в репозитории должен быть только код.

2023-11-21 14:57 UTC, alxmcs commented
Напоминаю, что я не телепат ![image](https://github.com/itsecd/python/assets/70561974/0a4a8ac7-6807-4fac-adb1-1986d6551ea3)

2023-11-22 07:50 UTC, alxmcs requested changes
Общие замечания:
* Отсутствует логирование полностью.
* Параметры работы приложения можно изменить только посредством редактирования исходного кода.  Должна быть предусмотрена возможность передавать параметры работы софта - либо через argparse, либо через dotenv, либо через json

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +import os
Порядок импортов не соответствует РЕР

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +def creating_files():
Нет докстринга, нет тайпхинтов

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +def creating_file_name(authors_rating, count):
Нет докстринга, нет тайпхинтов

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +def write_to_fail(book_title, overall_rating, authors_rating, full_review, file_name):
Нет докстринга, нет тайпхинтов

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +def getting_full_review():
Нет докстринга, нет тайпхинтов

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +    page += 1
Этот кусок бизнес-логики софта вынести в отдельную функцию

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +    page += 1
Исполняемый код модуля внести под `if __name__ == "__main__":`

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +    file_name = f"data_set/{number_of_stars} stars/{number_of_zeros}{number_of_reviews}"
Конкатенация путей должна быть через `os.path.join()`

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +        if not os.path.isdir(f"data_set/{i} stars"):
Конкатенация путей должна быть через `os.path.join()`

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +            os.mkdir(f"data_set/{i} stars")
Конкатенация путей должна быть через `os.path.join()`

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +    with open(file_name, "w+", encoding='utf-8') as file_review:
`+` в режиме работы с файловым потоком излишний

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +    url = f"https://www.livelib.ru/reviews/~{page}#reviews"
Захардкложенный параметр либо вынести в константы, либо вынести в настройки, либо вынести в значения параметров функции по умолчанию

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +while sum(count) <= 6000:
Захардкложенный параметр либо вынести в константы, либо вынести в настройки, либо вынести в значения параметров функции по умолчанию

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +        if count[int(float(authors_rating) // 1)] >= 1001:
Захардкложенный параметр либо вынести в константы, либо вынести в настройки, либо вынести в значения параметров функции по умолчанию

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +    number_of_zeros = zero[len(str(number_of_reviews))]
Это решается через форматный вывод численного значения, а не через этот кошмар

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +page = 2
Захардкложенный параметр либо вынести в константы, либо вынести в настройки, либо вынести в значения параметров функции по умолчанию

2023-11-22 07:50 UTC, alxmcs commented on Lab1/website_parse.py
> +            os.mkdir(f"data_set/{i} stars")
Нет обработки исключений вокруг манипуляций с файловой системой

2023-11-24 12:34 UTC, maeosha commented
почти все поправил, за исключением форматного вывода, немного не понял, что конкретно поправить

2023-11-25 13:55 UTC, alxmcs requested changes
Общее замечание: Не наблюдаю какого-либо логирования операций в софте. Пользователь запускает твое приложение и тупит в пустой экран до тех пор, пока софт не отработает.  Ты уверен, что он заслужил такое отношение к себе?

2023-11-25 13:55 UTC, alxmcs commented on Lab1/website_parse.py
> +    file_name: str = os.path.join("data_set", f"{number_of_stars} stars", f"{number_of_zeros}{number_of_reviews}")
```py
os.path.join("data_set", f"{number_of_stars} stars", f"{number_of_reviews:04}")
```

2023-11-25 13:55 UTC, alxmcs commented on Lab1/website_parse.py
> +def creating_files():
Тайпхинт возвращаемого значения все еще не появился

2023-11-25 13:55 UTC, alxmcs commented on Lab1/website_parse.py
> +    while sum(count) <= 6000:
Магическое число вынести в константы модуля или параметры софта

2023-11-25 13:55 UTC, alxmcs commented on Lab1/main.py
> +
Для кого все эти пустые строки?

2023-11-25 13:55 UTC, alxmcs commented on Lab1/website_parse.py
> +from selenium.common.exceptions import NoSuchElementException
Если это 

Должно было

Убедить меня

Что теперь импорты

Соответсвуют РЕР

То

Получилось

Не очень


Согласно РЕР сначала импортируются стандартные модуля, потом сторонние, потом локальные. Не нужно вставлять лишние щели между импортами

2023-11-25 13:55 UTC, alxmcs commented on Lab1/website_parse.py
> +        if count[int(float(authors_rating))] >= 1001:
Магическое число вынести в константы модуля или параметры софта

2023-11-25 13:55 UTC, alxmcs commented on Lab1/website_parse.py
> +            quit()
1. Вывод информации через `logging`
2. Не надо заставлять пользователя работать за твой софт при возникновении исключения

2023-11-25 13:55 UTC, alxmcs commented on Lab1/website_parse.py
> +    except:
Объект исключения проглочен

2023-11-25 13:55 UTC, alxmcs commented on Lab1/website_parse.py
> +        os.mkdir(os.path.join("data_set"))
Название директории захардкожено. Вынести в параметры функции

2023-11-25 14:11 UTC, maeosha commented on Lab1/website_parse.py
> +from selenium.common.exceptions import NoSuchElementException
так здесь же теперь все по pep отсортировано

2023-11-25 14:30 UTC, alxmcs commented on Lab1/website_parse.py
> +from selenium.common.exceptions import NoSuchElementException
Отсортировано
Но пустые строки лишние

2023-11-28 16:37 UTC, alxmcs requested changes
Почти

2023-11-28 16:37 UTC, alxmcs commented on Lab1/main.py
> +
второе ревью подряд пишу  замечание про эти пустые строки

2023-11-28 16:37 UTC, alxmcs commented on Lab1/website_parse.py
> +            continue
Может тут все-таки не `continue` нужно? Если необходимое количество файлов уже собрано?

2023-11-28 16:37 UTC, alxmcs commented on Lab1/main.py
> +my_variables = parser.parse_args()
Операция получения аргументов командной строки явно должна быть под `if __name__ == "__main__":`
В целом, туда можно и объявление аргументов спокойно перетащить

2023-11-28 16:37 UTC, alxmcs commented on Lab1/main.py
> +    start_parse(page, count, url, dir_name, max_txt_files)
Если бы аргументы в `start_parse` шли в немного другом порядке, 
```py
start_parse(count: Dict[int, int], page: int, url: str, dir_name: str, max_txt_files: int)
```
то можно было бы сэкономить на объявлении переменных
```py
start_parse(count, *my_variables)
```

2023-11-28 16:39 UTC, alxmcs requested changes

2023-11-28 16:39 UTC, alxmcs commented on Lab1/website_parse.py
> +        print("The 2'nd page is being parsed")
Пропустил кое-что:
Логирование через `logging`, никаких `print`

2023-11-28 18:31 UTC, maeosha commented on Lab1/website_parse.py
> +            continue
Ненене, это количество нужных файлов для одной из звезд, если я вижу, что я уже собрал достаточно пятизвездочных, то я просто их скипаю и продолжаю искать дальше. А так, спасибо вам за помощь очень много узнал за эту лабу

2023-11-29 12:42 UTC, alxmcs requested changes

2023-11-29 12:42 UTC, alxmcs commented on Lab1/main.py
> +    start_parse(count, my_variables)
Звездочка в примере кода в предыдущем ревью была не просто так - почитай про [распаковку](https://www.pythonforbeginners.com/basics/packing-in-python) (это буквально первая ссылка из гугла на какого-то индуса), приведи код во вменяемое состояние и давай закончим уже с первой лабой

2023-11-30 15:26 UTC, maeosha commented on Lab1/main.py
> +    start_parse(*my_variables)
ну кто же знал, что так работает, вы мне просто статью с распаковкой скинули, я прочитал и применил

2023-11-30 15:39 UTC, alxmcs approved these changes

2023-12-14 07:59 UTC, closed without merging