Вольгов Даниил Иванович 6213, Lab 3, Var 2
itsecd/python pull request #42
Opened 2022-12-05 12:11 UTC by the80hz

[dataset.csv](https://github.com/itsecd/python/files/10154018/dataset.csv)

2022-12-05 12:45 UTC, alxmcs requested changes
Не хватает докстрингов.

2022-12-05 12:45 UTC, alxmcs commented on Lab3/main_window.py
> +class MainWindow(QMainWindow):
Хотелось бы иметь возможность:
1) Видеть путь к выбранному фалу,
2) Возможность выбрать для работы другой файл без перезапуска программы.

2022-12-05 12:45 UTC, alxmcs commented on Lab3/main_window.py
> +                if row[0] == 'Date':
Нарисовалась проблема при открытии преобразованного датасета:
![image](https://user-images.githubusercontent.com/70561974/205636698-8f4a8d00-a61a-4697-b38f-2c1104202440.png)

Из-за того, что в преобразованном датасете есть пустые строки:
![image](https://user-images.githubusercontent.com/70561974/205636127-95358a3b-f312-4eb7-8551-d7915d665481.png)

2022-12-05 12:45 UTC, alxmcs commented on Lab3/main_window.py
> +    def split_years(self):
Из-за того, что тут нет проверки введенных в поле данных, можно спокойно уронить приложение, просто оставив в поле ввода текст, помещаемый туда при инициализации окна.
![image](https://user-images.githubusercontent.com/70561974/205638031-f27d4adb-215c-433d-b502-ea7d43c254b2.png)

![image](https://user-images.githubusercontent.com/70561974/205637679-0ffea7bd-bf0b-4288-9562-4a5267974060.png)

Соответственно, либо нужно вынести текст в отдельный лейбл, либо поискать в документации библиотеки, как настроить плейсхолдер текст.

2022-12-05 12:45 UTC, alxmcs commented on Lab3/main_window.py
> +    def split_weeks(self):
Тут аналогичная проблема

2022-12-05 12:45 UTC, alxmcs commented on Lab3/main_window.py
> +        self.table = QTableWidget(self)
Использовать таблицу, чтобы показывать единственную запись, это, конечно, оверкилл.
В целом, я не против, чтобы она осталась, если ее размер будет грамотно настроен, и эта неиспользуемая площадь исчезнет:
![image](https://user-images.githubusercontent.com/70561974/205639022-f01f7d08-3cee-48ba-b369-deaba06011df.png)

2022-12-05 12:45 UTC, alxmcs commented on Lab3/main_window.py
> +    def create_annots(self):
Смысла в создании аннотации для такого варианта, конечно, мало, но раз так было указано в задании, пусть остается.

2022-12-05 15:54 UTC, the80hz commented on Lab3/main_window.py
> +                if row[0] == 'Date':
решается таким образом:

2022-12-07 07:00 UTC, alxmcs approved these changes

2022-12-07 07:00 UTC, closed without merging