6213 Шестериков Б.В. Лаб.3 Вар.4
itsecd/python pull request #43
Opened 2023-11-22 21:44 UTC by BarMan555

Make GUI

2023-11-23 09:50 UTC, alxmcs requested changes
Скорллбары, это, в принципе, выход для того, чтобы показать изображение больше пиксмапа.
Но хотелось бы еще иметь возможность развернуть приложение на фуллскрин.
![image](https://github.com/itsecd/python/assets/70561974/efbcd8b0-4535-44a6-8762-8cfce5bd46e5)

2023-11-23 09:50 UTC, alxmcs commented on Lab3/get_way.py
Этот файл было бы лучше импортировать из `Lab2`, чтобы не дублировать код

2023-11-23 09:50 UTC, alxmcs commented on Lab3/iterator.py
Этот файл было бы лучше импортировать из `Lab2`, чтобы не дублировать код

2023-11-23 09:50 UTC, alxmcs commented on Lab3/make_csv.py
Этот файл было бы лучше импортировать из `Lab2`, чтобы не дублировать код

2023-11-23 09:50 UTC, alxmcs commented on Lab3/main_window.py
> +from iterator import *
`import *` - харам!

2023-11-23 09:50 UTC, alxmcs commented on Lab3/main_window.py
> +            self.msg_error()
У тебя работа по созданию аннотаций завязана на кучу захардкоженных папок. Хотя бы выведи объект исключения в мессаджбоксе, чтобы пользователь хотя бы отдаленное представление имел насчет того, почему его данные не подошли

2023-11-23 09:50 UTC, alxmcs commented on Lab3/main_window.py
> +            self.fold = QFileDialog.getExistingDirectory(self, "Select save path")
Это поле объявляется за пределами `__init()__`

2023-11-23 09:50 UTC, alxmcs commented on Lab3/main_window.py
> +            self.iter_tulip = ImgIterator(os.path.join(self.fold, "dataset.csv"), "tulip")
Из-за этой чехарды с путями шанс успешно сгенерить аннотацию близится к нулю. У меня аннотацию сгенерить вышло с 5 раза.

2023-11-23 09:50 UTC, alxmcs commented on Lab3/main_window.py
> +            make_csv(os.path.join(self.fold, "dataset"), img_classes, self.dataset_path, "normal", "")
Пользуясь случаем, хотелось бы передать привет функции генерации аннотаций - она крайне интересно делает свою работу
![image](https://github.com/itsecd/python/assets/70561974/eb190e82-8635-4de0-bcae-d8e985249e8e)

2023-11-23 16:26 UTC, BarMan555 commented on Lab3/main_window.py
> +            make_csv(os.path.join(self.fold, "dataset"), img_classes, self.dataset_path, "normal", "")
если честно не вижу, что здесь не так

2023-11-23 18:09 UTC, alxmcs commented on Lab3/main_window.py
> +            make_csv(os.path.join(self.fold, "dataset"), img_classes, self.dataset_path, "normal", "")
Имена файлов в сгенерированной по директории аннотации не соответствуют действительным

2023-11-25 14:18 UTC, alxmcs requested changes

2023-11-25 14:18 UTC, alxmcs commented on Lab2/make_csv.py
> +            for img in range(number_of_img):
Проблема с генерацией аннотации осталась на месте - если имена файлов - последовательные числа, то аннотация будет корректной. Если в директориях файлы со случайными названиями - нет.
`os.listdir` возвращает тебе список имен файлов, но ты им не пользуешься, а только узнаешь его длину . Это крайне сомнительное решение.

2023-11-25 14:18 UTC, alxmcs commented on Lab3/main_window.py
> +            'You did not choose a fold.'
Надеюсь, ты эффективно потратил те два символа, которые сэкономил в данном сообщении

2023-11-25 14:18 UTC, alxmcs commented on Lab3/main_window.py
> +            self.iter_rose = ImgIterator(os.path.join(self.fold, "dataset.csv"), "rose")
Все еще захардкожено название файла с аннотацией, хотя инструментария файлдиалога более чем достаточно, чтобы работать с аннотациями, которые могу называться как угодно

2023-11-25 14:18 UTC, alxmcs commented on Lab3/main_window.py
> +            self.iter_tulip = ImgIterator(os.path.join(self.fold, "dataset.csv"), "tulip")
Аналогичная история

2023-11-25 14:18 UTC, alxmcs commented on Lab3/main_window.py
> +    def next_rose(self):
`next_rose` и `next_tulip` отличаюся в коде буквально единственным параметром в вызове итератора. Почему бы не вынести его в параметры и не объединить функции? В #40 я показал пример как можно очень просто повесить на разные кнопки одну функцию с разными параметрами

2023-11-25 16:48 UTC, BarMan555 commented
Я искренне не понимаю почему не работает код на 237 строчке(

2023-11-25 17:12 UTC, alxmcs requested changes

2023-11-25 17:12 UTC, alxmcs commented on Lab3/main_window.py
> +        self.button_next_rose.clicked.connect(self.next_imagea("rose"))
> Я искренне не понимаю почему не работает код на 237 строчке(

Рискну предположить, потому что тут опечатка

2023-11-25 17:21 UTC, BarMan555 commented on Lab3/main_window.py
> +        self.button_next_rose.clicked.connect(self.next_imagea("rose"))
нет, это я экспериментировал с именем. Там и с next_image("rose") не работает

2023-11-25 17:25 UTC, BarMan555 commented
![Снимок экрана 2023-11-25 212440](https://github.com/itsecd/python/assets/40516567/2e0bbc77-499c-4ef8-b110-35228ad70a33)

Вылезает следующая ошибка

2023-11-25 17:35 UTC, alxmcs commented
В таком случае намекну, что ключевое слово `lambda` в #40 было использовано неспроста.
А зачем оно там все-таки надо и как работает биндинг акшонов на кнопки ты мне расскажешь в качестве одного из теоретических вопросов по лабе.

2023-11-27 14:44 UTC, alxmcs approved these changes

2023-11-29 10:00 UTC, closed without merging