Степан Можгаев Лабораторная 2 Вариант 7 6213-100503
itsecd/python pull request #46
Opened 2022-12-06 21:22 UTC by StepanMozhgaev

Написать скрипт для аннотаций
Написать скрипт копирования в другую директорию
Написать скрипт копирования в другую директорию с рандомными именами 
Написать скрипт next_element
Написать итератор

2022-12-26 12:26 UTC, StepanMozhgaev commented
Добрый день, возможно, лабораторная затерялась в куче других, прошу посмотреть её.

2022-12-26 13:27 UTC, alxmcs commented
> Добрый день, возможно, лабораторная затерялась в куче других, прошу посмотреть её.

Последнее занятие прошло сегодня, все ревью оставшихся лабораторных работ - после новогодних праздников и оплаты допчасов.

2022-12-26 14:51 UTC, StepanMozhgaev commented
Понял, спасибо

2023-02-27 18:00 UTC, alxmcs requested changes

2023-02-27 18:00 UTC, alxmcs commented on Lab2/copier.py
> +            print("No files found")
Нет вывода системной информации об ошибке

2023-02-28 05:39 UTC, alxmcs requested changes

2023-02-28 05:39 UTC, alxmcs commented on Lab2/Iter.py
> +    Iter = Iterator("C:\\Users\\0\\python_var_7\\dataset\\zebra\\0001.jpg")
Нарушение PEP - именование переменных

2023-02-28 05:39 UTC, alxmcs commented on Lab2/Iter.py
> +    возвращает следующий элемент
Это докстринг? Почему он здесь?

2023-02-28 05:39 UTC, alxmcs commented on Lab2/Iter.py
> +        путь к файлу
Аналогично

2023-02-28 05:39 UTC, alxmcs commented on Lab2/Data.py
> +        with open(os.path.join(path, self.directory, "annotation.csv"), "a", encoding="utf-8", newline="") as file:
Путь к аннотации все еще захардкожен

2023-02-28 05:39 UTC, alxmcs commented on Lab2/copier.py
> +        os.mkdir(os.path.join(path, "new_dataset"))
Если эта строка кода также может завершиться c `OSError` - этот блок try/except требует рефакторинга

2023-02-28 16:42 UTC, alxmcs approved these changes
Думаю, в таком виде работу можно зачесть

2023-02-28 16:42 UTC, closed without merging