6213 Акутин И.Д. Лаб.3 Вар.1
itsecd/python pull request #47
Opened 2023-11-25 16:05 UTC by Darktezi

2023-11-25 17:08 UTC, alxmcs requested changes
Общие замечания:
* А где requirements.txt и .gitignore для Lab3?
* Лейаут на фуллскрине может вызвать предынфарктное состояние у неподготовленного человека. Может, не стоит давать возможность разворачивать окно на фуллскрин?
![image](https://github.com/itsecd/python/assets/70561974/764f28c1-12e9-40a3-bdf1-e8c88b2573b8)
* Три кнопки `Create Dataset` выполняют действия по аналогичному сценарию. Различаются они только тем, какую функцию из 2 лабы вызывают в конце. Так как насчет убрать режим создания датасета в комбобокс?
![image](https://github.com/itsecd/python/assets/70561974/9b18c5ea-c4cc-4126-9026-aee6ba360df1)

2023-11-25 17:08 UTC, alxmcs commented on Lab3/main_window.py
> +        split_into_two(self.get_destination_folder())
Здесь и далее по коду: если нажать отмену в файлдиалоге, то приложение крашнется, ведь код продолжит исполняться дальше с пустым путем

2023-11-25 17:08 UTC, alxmcs commented on Lab3/main_window.py
> +        value = get_data_for_date(date)
Мне крайне не нравится, что софт настолько жестко привязан к данным, которые должны находиться в его рабочем каталоге

2023-11-25 18:38 UTC, Darktezi commented on Lab3/main_window.py
> +from get_value_from_date import get_data_for_date
Это модули из второй лабы. Код запускал, всё работает

2023-11-27 14:56 UTC, alxmcs requested changes

2023-11-27 14:56 UTC, alxmcs commented on Lab2/sort_csv.py
Помести уже все файлы из 2 лабы в эту ветку, мне надоело сшивать франкенштейна из двух веток каждый раз, когда мне хочется проверить, действительно ли у тебя рабочий код

2023-11-27 14:56 UTC, alxmcs commented on Lab3/main_window.py
> +            QtWidgets.QMessageBox.information(self, "Error", "You dont choose folder")
Вот эти 3 функции можно объединить в одну, параметризовав вызов метода из 2 лабы, и значительно сократить код модуля. Как это делать, уже обсуждалось в #40 и #46

2023-11-28 07:58 UTC, alxmcs approved these changes
Думаю, в текущем виде можно и заапрувить

2023-11-29 09:56 UTC, closed without merging