Панюшкин Андрей Михайлович 6213
itsecd/python pull request #5
Opened 2022-09-22 08:28 UTC by Santas7

Данная программа предназначена для парсинга картинок "rose" и "tulip" и сохранения полученных изображений в папку dataset/rose и dataset/tulip соответственно. Также мне необходимо было сохранить все файлы с названием (0001.jpg, 0002.jpg .... ). Для выполнения всех задач описаных в лабораторной работе я подключил следующие модули:
```
import os, shutil, requests
from bs4 import BeautifulSoup as BS
```
**По коду**:
Переменная url хранит в себе адрес "https://yandex.ru/images/" - базовый адрес.
Веб страничку получал через requests.get(), а непосредственно сам html-код через BS(request_go.content, "html.parser").
Через метод .findAll("img") - нашел все объекты с тегом <img>

```
request_go = requests.get(url + "search?text=" + name, headers={"User-Agent":"Mozilla/5.0"}) # получение веб-страницы, после чего можно получить всю необходимую нам информацию от объекта
html = BS(request_go.content, "html.parser") # html codes
data = [] # массив который будет хранить все теги <img>
finder = html.findAll("img") # нахождение всех тегов <img>
```

**В коде есть 4 функции, которые созданы для решения определенных задач**.
    1) save_image(image_url, name), где image_url - это ссылка на картинку (src), name - название текущего парсера (rose или tulip)
    2) clear_folder(name) - функция удаления папки
    3) check_folder() - функция проверки на существующую папку
    4) get_images_url(name) - функция получения картинки
В конце произвожу вызов основных функций:
```
check_folder() # проверка на сущестующую папку
get_images_url("rose") # вызов функции с "rose"
get_images_url("tulip") # вызов функции с "tulip"
```

**Хотел также отметить работу check_folder():**
Работа происходит через конструкцию try-except... в блоке try если папка не сущ-т, то создаю ее, иначе переходим в блок except и выполняем соответствующие команды.
```
def check_folder():
    try:
        os.mkdir("dataset")
    except:
        clear_folder("dataset")
        os.mkdir("dataset")
```

```
def clear_folder(name):  # функция удаления папки
    shutil.rmtree(name) # рекурсивно удаляет все дерево каталогов

```

**Также работа основной функции get_images_url(name)**
Начало разобрал ранее. Перейдем к циклу for. Цикл for нужен для пробежки по finder ( по спарсеному html-коду ). Далее в переменную image_url записываем ссылку которая содержится в теге **img**, в параметре src="...". Затем в массив data с помощью метода append добавляем в конец значение переменной image_url. После проверяем через условный оператор if строку на пустоту.... если не пустая, то сохраняем картинку в соответствующую папку dataset/name/....jpg/. После цикла выводим сообщение в консоль для пользователя. На этом работа функции закончена.
```
def get_images_url(name): # функция получения картинки
    request_go = requests.get(url + "search?text=" + name, headers={"User-Agent":"Mozilla/5.0"}) # получение веб-страницы, после чего можно получить всю необходимую нам информацию от объекта
    html = BS(request_go.content, "html.parser") # html codes
    data = [] # массив который будет хранить все теги <img>
    finder = html.findAll("img") # нахождение всех тегов <img>
    os.mkdir("dataset/" + name)
    for event in finder: # прогон по FINDER т.е по всем найденным тегам <img>
        image_url = event.get("src") # получаем ссылку из тега <img id="..." class="..." src="link">
        data.append([image_url])  # добавление элемента __IMAGE__URL__ в конец списка __DATA__
        if(image_url != ""): # проверка на пустую ссылку
            save_image(image_url, name) # сохранение картинки
    print("Nice save images)") # картинки успешно сохранены
    print(data)  # вывод ссылок в консоль для пользователя)
    global i
    i = 1
```
_Переменная i во всем коде используется для наименовения картинки ( при ее сохранении )_

2022-09-22 12:25 UTC, alxmcs commented on Lab1/main.py
> +        saver = open("dataset/" + name + "/" + "000" + str(i) + ".jpg", "wb") # открытие потока с типом wb
Вместо этой порнографии следует использовать f-строки
```python 
saver = open(f"dataset/{name}/000{str(i)}.jpg")
```

2022-09-22 12:29 UTC, alxmcs commented on Lab1/main.py
> +    if(i <= 9):
Аналогично, чтобы не городить эту совершенно проклятую конструкцию из if else, можно было воспользоваться форматированием строк:
saver = open(f"dataset/{name}/{i:04d}.jpg")

2022-09-22 12:30 UTC, alxmcs commented on Lab1/main.py
> +url = "https://yandex.ru/images/" # ссылка на страничку html
Согласно PEP костанты в модулях именуются КАПСОМ

2022-09-22 12:43 UTC, alxmcs commented on Lab1/main.py
> +i = 1
Использования глобальной переменной для решения такой задачи явно избыточно.
Здесь вполне можно обойтись локальной.

2022-09-22 12:52 UTC, alxmcs commented on Lab1/main.py
> +    request_on_download_image = requests.get("https:" + image_url) # получение веб-страницы
f-строки

2022-09-22 12:52 UTC, alxmcs commented on Lab1/main.py
> +    request_go = requests.get(url + "search?text=" + name, headers={"User-Agent":"Mozilla/5.0"}) # получение веб-страницы, после чего можно получить всю необходимую нам информацию от объекта
f-строки

2022-09-22 13:13 UTC, alxmcs requested changes
В задании указано:
`Именовать файлы необходимо порядковым номером (от 0 до 999).`
Этот код именует с 1 вместо 0.
 `Для каждого класса должно быть загружено не менее 1000 изображений.`
Этот код загружает по  43 изображения, это на 957 меньше необходимого.

2022-09-23 06:46 UTC, Santas7 commented
Здравствуйте! Я внес коррективы в мой код.. добавил f-строки, убрал лишний if-else, убрал комментарии которые портили весь код. Добавил цикл while в get_image_url() который проходит по всем page до 999 и парсит соответственно картинки.

2022-09-23 07:11 UTC, alxmcs commented
В таком случае
![image](https://user-images.githubusercontent.com/70561974/191908748-e088c0ab-9356-4db3-8a9d-f565a1b1c3b8.png)

2022-09-24 10:01 UTC, alxmcs reviewed
Осталось внести небольшие изменения, чтобы код был зачтен.

На будущее: в пул риквесте можно помечать мои придирки как resolved после того, как они исправлены.
![image](https://user-images.githubusercontent.com/70561974/192092048-cc7121ad-386b-485b-af32-fa1afd8cc3e5.png)

2022-09-24 10:06 UTC, Santas7 commented on Lab1/main.py
> +def clear_folder(name):
просто так понятнее мне кажется

2022-09-24 10:11 UTC, Santas7 commented on Lab1/main.py
> +def clear_folder(name):
удалил

2022-09-24 10:24 UTC, alxmcs commented on Lab1/main.py
> +def clear_folder(name):
Если это был лютый ван-лайнер с максимально неочевидным лист компрехеншеном, то смыл, может быть, и был бы.

В данном случае, это просто вызов функции из библиотеки с передачей параметра без изменений.
При функция из библиотеки задокументирована лучше, чем та функция, что ее оборачивает в твоем коде:
![image](https://user-images.githubusercontent.com/70561974/192092788-54fa0edc-5355-4515-aeef-8c722ac55b1e.png)

Что тут понятнее - вопрос риторический.

2022-09-25 11:20 UTC, alxmcs requested changes
Осталась мелочь, о которой я запамятовал - `requirements.txt` и `.gitignore`

2022-09-25 11:26 UTC, alxmcs reviewed
Еще некоторые мелочи

2022-09-25 11:26 UTC, alxmcs commented on Lab1/main.py
> +help(get_images_url.__doc__)
`help()` на реализованные функции можно опустить

2022-09-25 11:26 UTC, alxmcs commented on Lab1/main.py
> +check_folder()
Вызов реализованных в твоем модуле функций лучше поместить под 
```py
if __name__ == "__main__":
```
Чтобы при импорте этого кода он не начинал исполняться

2022-09-25 13:30 UTC, alxmcs requested changes
Все еще нет ни `.getignore`, ни `requirements.txt`

2022-09-25 13:30 UTC, alxmcs commented on Lab1/main.py
> +help(get_images_url.__doc__)
Этот код можно удалить. Более того, он исполнится при импорте модуля, что нежелательно.

2022-09-25 14:06 UTC, alxmcs approved these changes
Похоже, что теперь меня все более-менее устраивает
Ура
:partying_face:

2022-09-25 14:06 UTC, Santas7 commented
ура! спасибо!

2022-09-25 14:06 UTC, closed without merging