6213 Козловская К. А. Лаб.3 Вар.8
itsecd/python pull request #59
Opened 2023-11-28 17:49 UTC by Pomi44

2023-11-29 10:26 UTC, alxmcs requested changes

2023-11-29 10:26 UTC, alxmcs commented on Lab3/main_window.py
> +from PyQt6.QtWidgets import QWidget, QApplication, QMainWindow, QLabel, QPushButton, QVBoxLayout, QFileDialog, QMessageBox, QTextBrowser, QComboBox, QInputDialog
Нарушение РЕР - длина строки

2023-11-29 10:26 UTC, alxmcs commented on Lab3/main_window.py
> +                        )
Эти два метода практически идентичны, их можно объединить в один, добавив параметр для вызова соответствующего метода из 2 лабы (желательно енамом).
Как повесить один и тот же хендлер с разными параметрами на два события обсуждалось в #40 и #46

2023-12-04 17:44 UTC, alxmcs requested changes
Осталась одна мелочь

2023-12-04 17:44 UTC, alxmcs commented on Lab3/main_window.py
> +from PyQt6.QtWidgets import QWidget, QApplication, QMainWindow, QLabel, QPushButton, QVBoxLayout, QFileDialog, QMessageBox, QTextBrowser, QComboBox, QInputDialog
Осталось привести эту строку к РЕР по длине

2023-12-04 19:41 UTC, Pomi44 commented
забыла сохранить

2023-12-05 07:57 UTC, alxmcs approved these changes

2023-12-14 07:59 UTC, closed without merging