Вольгов Даниил Иванович 6213, Lab 1, Var 2
itsecd/python pull request #6
Opened 2022-09-24 18:30 UTC by the80hz

От меня требовалось с использованием сервиса gismeteo получить данные о погоде в Самаре за максимально возможный промежуток времени. Необходимо копировать дату, температура, давление, ветер.

Использовал библиотеку csv чтобы производить запись данных в .csv файл. 
Использовал библиотеку bs4 для анализа дерева html.

Ну, оно просто работает, больше добавить нечего...

2022-09-25 11:41 UTC, alxmcs requested changes
Код должен быть как минимум логически (в целом, можно и физически) декомпозирован, то есть  разбит на отдельные функции с вменяемыми:
* названиями,
 * наборами параметров,
 * докстрингами, тайпхинтами.
 
Вызовы функций для решения задачи лабораторной должны быть под 
```py
if __name__ == "__main__":
```
чтобы код модуля не исполнялся при его импорте.

Сплошное полотнище из кода на 2 курсе уже должно быть стыдно сдавать.

2022-09-25 11:41 UTC, alxmcs commented on Lab1/main.py
> +with open('dataset.csv', 'w+', encoding='utf8') as database:
Логической декомпозиции кода в модуле нет вообще. Это харам.

2022-09-25 11:41 UTC, alxmcs commented on Lab1/main.py
> +with open('dataset.csv', 'w+', encoding='utf8') as database:
`database` явно не подходящее название для переменной для записи в csv-файл.

2022-09-25 11:41 UTC, alxmcs commented on Lab1/main.py
> +with open('dataset.csv', 'w+', encoding='utf8') as database:
Меня не устраивает то, что имя результирующего файла захардкожено

2022-09-25 11:41 UTC, alxmcs commented on Lab1/main.py
> +year = 2008
То, что начальные значения для года и месяца захардкожены, меня тоже не устраивает

2022-09-25 11:41 UTC, alxmcs commented on Lab1/main.py
> +import requests
В проекте нет `requirements.txt`

2022-09-25 12:51 UTC, the80hz commented
Добавил небольшие докстринги, разбил скрипт на функции, и переименовал некоторые переменные

2022-09-25 13:50 UTC, alxmcs requested changes
Изменения в коде произошли. Они крайне невпечатляющие.

2022-09-25 13:50 UTC, alxmcs commented on Lab1/main.py
> +def request(url):
Бессмысленно выделять в отдельную функцию единственный вызов метода готовой библиотеки

2022-09-25 13:50 UTC, alxmcs commented on Lab1/main.py
> +    with open('dataset.csv', 'w+', encoding='utf8') as dataset:
Вот этот код должен находиться внутри отдельной функции.
И путь к результирующему файлу должен быть передан в нее в качестве параметра, который необходимо еще и проверить на корректность.

2022-09-25 13:50 UTC, alxmcs commented on Lab1/main.py
> +    print(write_table.__doc__)
Не думаю, что демонстрация докстрингов функций жизненно необходима при каждом запуске кода

2022-09-25 13:50 UTC, alxmcs commented on Lab1/main.py
> +        year = 2008
Все еще захардкожено

2022-09-25 13:50 UTC, alxmcs commented on Lab1/main.py
> +        month = 1
Все еще захардкожено

2022-09-25 13:50 UTC, alxmcs commented on Lab1/main.py
> +    MONTH = datetime.now().timetuple().tm_mon
Эти значения - не константы, соответственно, не должны быть капсом.
Боле того, они используются в коде только раз и получены через один и тот кортеж.

2022-09-25 13:50 UTC, alxmcs commented on Lab1/main.py
> +    URL = 'https://www.gismeteo.ru/diary/4618'
Если это необходимая в коде константа, то ей тут не место. Если нет - то она не должна быть капсом.

2022-09-25 13:55 UTC, the80hz commented on Lab1/main.py
> +        year = 2008
Получается нужно вместо `year = 2008` написать `min_year = 2008`? Или не в этом заключается хардкод?

2022-09-25 14:00 UTC, alxmcs commented on Lab1/main.py
> +        year = 2008
Значение этой переменной должно быть доступно для передачи пользователем в качестве входного параметра какой-либо функции, внутри которой этот код должен находиться

2022-09-25 16:42 UTC, alxmcs requested changes

2022-09-25 16:42 UTC, alxmcs commented on Lab1/main.py
> +    URL = 'https://www.gismeteo.ru/diary/4618'
[Константы](https://peps.python.org/pep-0008/#constants) объявляются на уровне модуля, чтобы была возможность их импортировать в другой код.
Либо это просто переменная, тогда она должна быть не капсом.
Либо это константа, тогда она должна быть на уровне модуля.

2022-09-26 05:00 UTC, alxmcs approved these changes
Теперь сгодится

2022-09-26 05:00 UTC, closed without merging