6213 Ксеневич Максим Лаб2, Вар10
itsecd/python pull request #62
Opened 2023-11-29 21:39 UTC by maeosha

работа с тем, что напарсили, и создание класса итерации

2023-11-30 08:08 UTC, alxmcs commented
Не пробовал сначала получить аппрув по 1 лабе?

2023-12-01 08:18 UTC, alxmcs requested changes
Общее замечание: 
Грамотно декомпозировать эту кашу из костылей и самокопирования. 
И привести код к состоянию, когда он сможет действительно запуститься и отработать, а не жидко пернуть и помереть на 46 строке `main.py`.

2023-12-01 08:18 UTC, alxmcs commented on Lab2/create_csv_file.py
> +    logging.info(f"{csv_name} successfully created!")
отличается от этой?
Кроме докстринга

2023-12-01 08:18 UTC, alxmcs commented on Lab2/create_csv_file.py
> +    make_csv(file_info_list, csv_name)
от этой только наличием какого-то странного костыля с вытаскиваением рейтинга из имени директории

2023-12-01 08:18 UTC, alxmcs commented on Lab2/create_copy.py
> +    shutil.copy(path_copied_file, path_new_file)
Опять совершенно одинаковые функции - эта

2023-12-01 08:18 UTC, alxmcs commented on Lab2/create_random.py
> +    shutil.copy(path_copied_file, path_random_file)
И эта

2023-12-01 08:18 UTC, alxmcs commented on Lab2/gitignore
Неверное название файла

2023-12-01 09:50 UTC, maeosha commented on Lab2/main.py
> +                    help='the name of the file with random placement of txt files')
Это реализовывать тож через аргпарс? Или через что-то другое?

2023-12-01 10:00 UTC, alxmcs commented on Lab2/main.py
> +                    help='the name of the file with random placement of txt files')
Это твой софт, ты волен имплементировать его функционал так, как сочтешь нужным. А я волен быть недовольным результатами имплементации в ревью, если на это есть причины

2023-12-07 11:44 UTC, alxmcs requested changes

2023-12-07 11:44 UTC, alxmcs commented on Lab2/content.py
> +def fail_path_information(data_dir_name: str, new_dir_name: str, processing_method: int, random_list: list) -> list:
>fail
<img src="https://github.com/itsecd/python/assets/70561974/3189dbb9-55fe-4d52-b399-f5f8ca5e5193"  width=250/>

2023-12-07 11:44 UTC, alxmcs commented on Lab2/content.py
> +        shutil.copy(path_copied_files[i], path_new_files[i])
Добавить обработку исключений

2023-12-07 11:44 UTC, alxmcs commented on Lab2/content.py
> +                logging.warning("The wrong item has been selected!", NameError)
Аналогично - enum

2023-12-13 09:00 UTC, maeosha commented
Извините, но иой пул реквестик уже 4 дня ревью ждет, он проголодался.... (

2023-12-13 12:22 UTC, alxmcs requested changes

2023-12-14 06:41 UTC, alxmcs approved these changes

2023-12-14 08:00 UTC, closed without merging