Laba 3 Жидяев Дмитрий 6213 Вар 4
itsecd/python pull request #62
Opened 2022-12-25 13:11 UTC by Dmitrii14

2023-02-10 08:44 UTC, alxmcs commented
Перед тем, ка кчто-то делать по 3 лабе, я бы рекомендовал закончить сдачу 2й

2023-02-24 08:56 UTC, alxmcs requested changes
Данное приложение потрясающе гармонично - оно ужасно как снаружи, так и изнутри.

Начальный размер окна не адаптирован под элементы.
![image](https://user-images.githubusercontent.com/70561974/221132442-14f3f6c8-c405-4c68-9df2-7b6f6df6417e.png)

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +            print("error")
Нет вывода системного сообщения об ошибке

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +            print("error")
Нет вывода системного сообщения об ошибке

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +            print("error")
Нет вывода системного сообщения об ошибке

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +            print("error")
Нет вывода системного сообщения об ошибке

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +            метод перехода к следующей картинки
Нет описания параметров в докстринге

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +        self.setWindowTitle("Main window")
Можно было бы назвать окно пооригинальнее

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +        self.dataset_path = QFileDialog.getExistingDirectory(self, 'Путь к папке базового датасет')
У пользователя должна быть возможность сменить используемый датасет без перезапуска программы

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +        self.s_p_rose = os.path.join("dataset", CLASS_DEFAULT[Type.ROSE.value], "0001.jpg")
Этот путь захардкожен.
Более того, этот захардкоженный путь к изображению будет корректен только тогда, когда пользователь выберет в качестве пути для работы с датасетом директорию рядом с исполняемым файлом.
А у пользователя должна быть возможность работать с корректной стуктурой папок, содержащей датасет картинок вне засисмости от того, где она расположена.

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +        self.s_p_tulip = os.path.join("dataset", CLASS_DEFAULT[Type.TULIP.value], "0001.jpg")
Аналогично

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +        src = QLabel(f'Базовый датасет:\n{self.dataset_path}', self)
Это единственное место в коде, где используется путь к папке, выбранной пользователем.
В остальный случаях используются захардкоженные пути к папке внутри проекта.
Очевидно, что так быть явно не должно.

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +    def add_button(self, name: str, size_x: int, size_y: int, pos_x: int, pos_y: int):
Нет тайпхинта возвращаемого значения

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +    def next(self, image_path: str, index: int, count: int):
Нет тайпхинта возвращаемого значения

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +    def create_annotation(self):
Нет тайпхинта возвращаемого значения

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +    def copy_of_dataset(self):
Нет тайпхинта возвращаемого значения

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +    def random_of_dataset(self):
Нет тайпхинта возвращаемого значения

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +    def exit(self):
Нет тайпхинта возвращаемого значения

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +        self.btn_random_of_dataset = self.add_button("Рандомное датасет", 140, 50, 630, 150)
>"Копирование датасет"
>"Рандомное датасет"

У тебя случился инсульт во время именования кнопок? 
У кнопок должны появиться связные грамотные названия

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +        self.btn_copy_of_dataset = self.add_button("Копирование датасет", 140, 50, 630, 100)
Аналогично

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +                image_path = os.path.join("dataset", CLASS_DEFAULT[index], "0001.jpg")
Захардкоженный путь к файлу

2023-02-24 08:56 UTC, alxmcs commented on Lab3/MainWindow.py
> +                next = IteratorOfExemplar("annotation.csv", image_path).__next__()
Захардкоженный путь к аннотации.
Здесь бы не помешало использовать тот самый филд `self.dataset_path`, который, почему-то нигде кроме лейбла в окне не используется.

2023-02-25 16:45 UTC, Dmitrii14 commented on Lab3/MainWindow.py
> +        self.dataset_path = QFileDialog.getExistingDirectory(self, 'Путь к папке базового датасет')
Это нужно реализовать путем добавления кнопки выбора используемого датасета?

2023-02-26 13:15 UTC, alxmcs requested changes
На всякий случай опишу несколько очевидных вещей:
Пользователь приложения должен иметь возможность указать для работы директорию, в которой лежит предопределенный набор файлов и папок примерно такого вида:
/annotation.csv
/tulip
--/0000.jpg
...
--/0ххх.jpg
/rose
--/0000.jpg
...
--/0ххх.jpg

Данная структура может лежать по любому пути на машине пользователя, но сама она постоянна.

Пользователь должен иметь возможность в любой момент сменить директорию (соответственно, на форме должен быть акшон, позволяющий это сделать).

Пути к папке, в которой лежит датасет более чем достаточно, чтобы определить пути к демонстрируемым изображениям (или факт их отсутствия).

Заключительная очевидная вещь: подавляющее число твоих одногруппников справилось с данной лабораторной. Никто не запрещает тебе посмотреть код закрытых пул-риквестов, чтобы понять, что в твоем коде не так.

2023-02-26 13:15 UTC, alxmcs commented on Lab3/MainWindow.py
> +        self.dataset_path = QFileDialog.getExistingDirectory(self, 'Путь к папке базового датасет')
Очевидно, что да

2023-02-26 13:15 UTC, alxmcs commented on Lab3/MainWindow.py
> +        self.s_p_rose = QFileDialog.getOpenFileName(self, 'Путь к первой розе')
Зачем спрашивать пользователя о пути к перым изображениям, если он уже указал путь к датасету?
Это совершенно бессмысленно

2023-02-26 13:15 UTC, alxmcs commented on Lab3/MainWindow.py
> +        self.s_p_tulip = QFileDialog.getOpenFileName(self, 'Путь к первому тюльпану')
Аналогично

2023-03-01 08:09 UTC, alxmcs approved these changes
Думаю, что в таком виде это можно зачесть

2023-03-01 08:09 UTC, closed without merging