6213 Сулейманян А.В Лабораторная 1 вариант 8
itsecd/python pull request #68
Opened 2023-12-10 17:11 UTC by bonyfa

В этот раз вроде оформил все правильно

2023-12-11 09:46 UTC, alxmcs requested changes

2023-12-11 09:46 UTC, alxmcs commented on Lab2/copy_dataset.py
> +    Функция копирывания и изменения имени датасета рандомом и нет
>копирывания 

Эта дисциплина не посвящена изучению русского языка, но все-таки

2023-12-11 09:46 UTC, alxmcs commented on Lab2/copy_dataset.py
> +            output_path =output_path +"/"+name_of_output_file
Конкатенация путей должна быть через `os.path.join()`

2023-12-11 09:46 UTC, alxmcs commented on Lab2/copy_dataset.py
> +def copy_and_rename_dataset(input_path: str, output_path: str, name_of_output_file: str, RANDOM :bool) -> None:
Именование переменной `RANDOM` не по РЕР

2023-12-11 09:46 UTC, alxmcs commented on Lab2/copy_dataset.py
> +                            shutil.copy(input_file_path, output_file_path)
Эти два варианта отличаются только на 21-23 и 31 строках - соответственно, только эта логика и должна находиться под `if`

2023-12-11 09:46 UTC, alxmcs commented on Lab2/copy_dataset.py
> +                            new_file_name = f"{class_label}_{file}"
Почему файл без расширения?

2023-12-11 09:46 UTC, alxmcs commented on Lab2/copy_dataset.py
> +                            random_number = random.randint(0, 10000)
При повторении гсч случайного числа файл будет перезаписан

2023-12-11 09:46 UTC, alxmcs commented on Lab2/copy_dataset.py
> +    return None
Зачем?

2023-12-11 09:46 UTC, alxmcs commented on Lab2/copy_dataset.py
> +    RANDOM = False
Нарушение РЕР при именовании переменной

2023-12-11 10:54 UTC, bonyfa commented on Lab2/copy_dataset.py
> +                            new_file_name = f"{class_label}_{file}"
Так в переменной file уже есть расширение .txt

2023-12-11 10:56 UTC, bonyfa commented on Lab2/copy_dataset.py
> +    return None
Вы про return None?Если да то в прошлой лабе вы мне говорили так делать

2023-12-11 12:02 UTC, alxmcs commented on Lab2/copy_dataset.py
> +    return None
Я писал про тайпхинт возвращаемого значения, а не про директиву `return None`

2023-12-11 12:12 UTC, alxmcs requested changes

2023-12-11 12:12 UTC, alxmcs commented on Lab2/copy_dataset.py
> +                            random_number = random.randint(0, 10000)
И ты не планируешь с этим ничего делать, как я понимаю?

2023-12-11 12:12 UTC, alxmcs commented on Lab2/iterator.py
> +        self.output_file_ = output_file_
Если это модификатор доступа, но он должен быть с другой стороны
Если нет, то это нарушение РЕР в именовании поля класса

2023-12-11 12:12 UTC, alxmcs commented on Lab2/iterator.py
> +    def __iter__(self):
Слишком много пустых строк

2023-12-11 14:15 UTC, alxmcs commented on Lab2/copy_dataset.py
> +                            random_number = random.randint(0, 10000)
Сколько ревью подряд мне писать об этой строке кода?

2023-12-11 14:17 UTC, alxmcs commented on Lab2/copy_dataset.py
> +            output_path = os.path.join(output_path, "/", name_of_output_file)
` os.path.join` как раз нужен для того, чтобы не ставить слеши руками
Зачем передавать в него слеш в виде аргумента?

2023-12-11 14:17 UTC, alxmcs commented on Lab2/copy_dataset.py
> +def copy_and_rename_dataset(input_path: str, output_path: str, name_of_output_file: str, random_or_not :bool) -> None:
Мало пустых строк

2023-12-11 14:18 UTC, alxmcs commented on Lab2/create_annotation.py
> +                                        'class_label': class_label})
И зачем ты заводил константы? Чтобы ими никак не пользоваться?

2023-12-11 14:57 UTC, bonyfa commented on Lab2/copy_dataset.py
> +                            random_number = random.randint(0, 10000)
То есть каждый раз когда я генерирую одно рандомное число у меня перезаписываются все файлы?

2023-12-12 08:51 UTC, alxmcs requested changes

2023-12-12 12:05 UTC, bonyfa commented on Lab2/copy_dataset.py
> +                            random_number = random.randint(0, 10000)
Ниже нее есть  while который проверяет переменную на уникальность и если она не уникальна заново генерирует ее, сохраняя все использованные значения

2023-12-12 13:15 UTC, bonyfa commented
Ниже нее есть while который проверяет переменную на уникальность и если она не уникальна заново генерирует ее, сохраняя все использованные значения

2023-12-12 14:10 UTC, alxmcs requested changes

2023-12-12 14:10 UTC, alxmcs commented on Lab2/copy_dataset.py
> +                            existing_random_numbers.add(random_number)
Логичнее и вычислительно эффективнее было бы создать заранее множество (потому что поиск его элемента - `О(1)`, а поиск элемента в списке - `O(n)`)  и предзаполнить его случайными значениями вплоть до нужного размера.
Вместо того, чтобы для каждого файла проходить в цикле имеющиеся значения, да еще и пополнять их/генерировать номер заново.

2023-12-13 12:12 UTC, alxmcs approved these changes

2023-12-14 08:00 UTC, closed without merging