6213 Сахарова Дарья Лаб.1 Вар.7
itsecd/python pull request #7
Opened 2022-09-25 19:31 UTC by daryaskhrv

Сформировать запросы для поиска изображений, контент на которых соответствует классам zebra и bay horse. Для каждого класса должно быть загружено не менее 1000 изображений. Изображения для каждого класса должны находиться в подпапке папки dataset с соответсвующим названием.

2022-09-25 19:36 UTC, daryaskhrv reviewed
6213 Вар7 Сахарова

2022-09-26 06:38 UTC, alxmcs requested changes
В задании явно указано:
`Для каждого класса должно быть загружено не менее 1000 изображений`
Данный код сохраняет на 956 изображений зебр меньше требуемого и на 966 изображений лошадей меньше требуемого.
![image](https://user-images.githubusercontent.com/70561974/192208954-f6e3dc05-73b6-4598-b966-45732b5ddc23.png)

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +def main():
Название `main`  явно не отражает то, какую работу данная функция выполняет.

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +    KEY2 = "bay horse"
[Константы](https://peps.python.org/pep-0008/#constants) объявляются на уровне модуля, чтобы была возможность их импортировать в другой код.
Либо это просто переменная, тогда она должна быть не капсом.
Либо это константа, тогда она должна быть на уровне модуля.

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +    print("is_valid - ",is_valid.__doc__)
Выводить докстринги к функциям модуля необходимости нет.

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +    amount2 = get_and_download(URL, KEY2)
Код для получения изображений по `KEY1` и `KEY2` дублируется.  Стоит зарефаторить этот участок кода, чтобы получать изображения по списку ключей.

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +    save = open(f"{pathname}/{str(index).zfill(4)}.jpg", "wb")
Для комбинирования путей стоит использовать `os.path.join`

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +
Пустая строка. Зачем?

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +
В [PEP](https://peps.python.org/pep-0008/#blank-lines) описано число пустых строк между функциями. Это не то число пустых строк.

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +
В [PEP](https://peps.python.org/pep-0008/#blank-lines) описано число пустых строк между функциями. Это не то число пустых строк.

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +
В [PEP](https://peps.python.org/pep-0008/#blank-lines) описано число пустых строк между функциями. Это не то число пустых строк.

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +
В [PEP](https://peps.python.org/pep-0008/#blank-lines) описано число пустых строк между импортами и последующим кодом. Это не то число пустых строк.

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +
Пустая строка. Зачем?

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +
В [PEP](https://peps.python.org/pep-0008/#blank-lines) описано число пустых строк между функциями. Это не то число пустых строк.

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +
В [PEP](https://peps.python.org/pep-0008/#blank-lines) описано число пустых строк между функциями. Это не то число пустых строк.

2022-09-26 06:38 UTC, alxmcs commented on Lab1/sourse.py
> +    URL = "https://yandex.ru/images/"
Логичнее было бы видеть url и ключи в качестве входных параметров этой функции.

2022-09-26 11:01 UTC, alxmcs requested changes
Остались небольшие доработки

2022-09-26 11:01 UTC, alxmcs commented on Lab1/sourse.py
> +    i = 1
Именование картинок в условии лабораторной начинается с нуля.

2022-09-26 11:33 UTC, alxmcs approved these changes

2022-09-26 11:38 UTC, closed without merging