6213 Ненашев Дмитрий Михайлович Лаб.5 Вар.5
itsecd/python pull request #74
Opened 2023-02-27 14:40 UTC by neygenius

1. Разделить набор данных на сбалансированные выборки,
2. При помощи PyTorch реализовать модель нейронной сети,
3. Обучить модель и оценить качество обучения.

2023-02-27 16:13 UTC, alxmcs requested changes
Нет комментария о результате обучения сети - овефитнулась/андерфитнулась ли сеть или обучение сети завершилось более-менне успешно.

2023-02-28 16:41 UTC, alxmcs requested changes
Так сеть обучилась или переучилась?
Жду аргументов в пользу какого-то из этих вариантов

2023-02-28 18:03 UTC, neygenius commented
Я предполагаю, что сеть немного недообучилась, т.к. значительных расхождений в точности на графиках нет, но с тестовой выборкой она справляется плохо (вероятно проблема в малом датасете)

2023-03-01 08:29 UTC, alxmcs approved these changes
Я бы сказал, что она, наоборот переобучилась.
Впрочем, какого-то глубокого знания темы машинного обучения требовать на 2 курсе излишне.
Зачел.

2023-03-01 08:29 UTC, closed without merging